operator-framework/operator-controller

api/v1alpha1/platformoperator_types.go, config/crd/bases/platform.openshift.io_platformoperators.yaml
Adds a description to the `spec.packageName` field, making its purpose more clear to those reviewing the API. This change also adds the information to the generated PO CRD description, which can be then be viewed on-cluster via `kubectl explain`.
=> Add PO spec.packageName description

go.mod, go.sum
Update the rukpak API dependency to the v0.4.0 release which added declarative BI support.
=> go.*: Bump rukpak module dependency

.github/workflows/ci.yaml, Dockerfile, Makefile, controllers/platformoperator_controller.go, main.go
Home for any commits that are needed in order to get a basic e2e testing suite introduced.
=> Ensure the platform operator stack is deployed before running e2e tests

Makefile, controllers/platformoperator_controller.go, go.mod, go.sum, test/e2e/controller_test.go
Update the rukpak dependency to my rukpak fork's v0.5.0 release which builds on top of https://github.com/operator-framework/rukpak/pull/387 and rips out OperatorConditions handlement.
=> Add barebones registry+v1 bundle format support

Makefile, go.mod, go.sum
Move off the fork of rukpak to rely on the upstream repository directly
=> makefile: Update rukpak repository

Makefile
Add an additional check for the conditions of all the OLM CRDs
to be accepted ("NamesAccepted") before attempting to install additional
OLM resources. This prevents flakes when running the olm target on CI.
Closes #29
=> Makefile: add conditions check to OLM installation

controllers/cs_adapter_controller.go
Update the CS adapter logic, and ensure that the extra, registry+v1
bundle identifiable information is surfaced as Input
metadata.Annotations. This enables clients, e.g. a lookup service, to be
able to map an installed ID to an Input's metadata.Name, and access the
properties they care about.
In the case of a rukpak-focused client, we're mainly interested in
finding the bundle container image reference of the resolved Input
resource. Surfacing that container image as an annotation allows the
client to quickly lookup this property without iterating of an array
of the Input's spec.Properties.
In the future, we may want to re-think this approach, as other
resolution use cases may require building constraints on top of these
identifiable properties (e.g. a cluster invariant that only allows …
=> controllers: Propagate the registry+v1 identifying information as Input annotations

controllers/cs_adapter_controller.go, controllers/platformoperator_controller.go, internal/sourcer/registry_sourcer.go, internal/sourcer/sourcer.go, test/e2e/adapter_test.go, test/e2e/e2e_suite_test.go, test/e2e/platform_operators_test.go
Updates the PO controllers, and ensure that resolution decisions are surfaced as status conditions. When resolutions fails, we should bubble up that status, and reset it when a successful resolution has occurred for the underlying Resolution object we're managing.
Refactor the Resolution requeue logic in the PO controllers, and avoid having explicit code that filters out POs that aren't named "cluster", as it's incompatible with our current testing suite, and that can be handled better at the caching layer.
=> feat: Add basic status conditions management to the PO controller

api/v1alpha1/operator_types.go, config/crd/bases/core.olm.io_operators.yaml, config/samples/operator_v1alpha1_operator.yaml, internal/controllers/operator_controller.go, internal/sourcer/registry_sourcer.go, test/e2e/operators_test.go
Pushing up local changes that I had staged. Updates the Operator API and introduces an optional spec.package.version string field. When this field has been unspecified, the expected behavior is that the highest semver bundle that meets the package constraints will be returned.
The spec.package.version field supports a user specifying either an explicit version (e.g. "2.0.1") or a version range (e.g. "<2.0.0 || >=3.0.0"). When reconciling this value, we attempt to first check whether an explicit version has been specified through a simple regex, and then fall back to parsing a version range.
=> *: Implement support for reconciling Operator version constraints

Makefile, cmd/main.go, internal/sourcer/registry_sourcer.go, test/e2e/operators_test.go
Update the CatalogSource registry implementation, and ensure that an Operator tracks the catalog source that was initially selected during installation when no spec.Catalog configuration has been specified by the user.
In the case that multiple catalogs exist on the cluster (e.g. c1, c2, ..., cN) and a subset of those catalogs all contain the same package name, then the expected behavior is that one of those catalogs that contains the highest semver bundle will be selected during installation. After installation, a different catalog has been updated and now contains the highest semver bundle in the desired package name. We'd like to prohibit an Operator upgrading to another catalog source in this case to avoid the scenario where packages within those different catalogs define different …
=> internal,test: Ensure cross-catalog upgrades are prohibited

api/v1alpha1/operator_types.go, config/crd/bases/operators.operatorframework.io_operators.yaml, config/samples/operators_v1alpha1_operator.yaml
Addresses Issue #69 
Add package name to spec with validation, clear generated comments, run make, update sample CR
Tested by running:
```
kind create cluster
make install
kubectl apply -f config/samples/operators_v1alpha1_operator.yaml
```
=> Operator Spec PackageName

go.mod, go.sum, internal/resolution/deppy.go
Imports deppy library into project
Closes: #71 
Signed-off-by: perdasilva <perdasilva@redhat.com>
=> Import deppy into project

.github/workflows/go-apidiff.yaml, .github/workflows/unit-test.yaml
* add go-apidiff workflow to run on all PRs (informational to make sure we're aware of Go API changes)
* add go module caching to speed up builds and tests
=> github workflow additions/updates

Dockerfile, api/v1alpha1/operator_types.go, controllers/operator_controller.go, controllers/suite_test.go, internal/util/util.go
Make sure each condition is defined (as best we can)
Enhancements to #91
Signed-off-by: Todd Short <tshort@redhat.com>
=> Add additional unit-tests for Conditions

internal/resolution/variable_sources/entity/bundle_entity_test.go, internal/resolution/variable_sources/required_package/required_package.go, internal/resolution/variable_sources/required_package/required_package_test.go
This PR adds the `RequiredPackage` variable source for generating required package variables from package names
=> [resolution pt.2] required package variable source

internal/resolution/variable_sources/bundles_and_dependencies/bundles_and_dependencies.go, internal/resolution/variable_sources/bundles_and_dependencies/bundles_and_dependencies_test.go, internal/resolution/variable_sources/entity/bundle_entity.go
This PR adds the `Bundles and Dependencies` variable source. It generate `BundleVariables` for all `RequiredPackage` variables found from executing the `inputVariableSource`s. It does so by inspecting the `BundleEntities` included in each `RequiredPackageVariable`, resolving dependencies, and outputting `BundleVariables` for all `BundleEntities` and their resolved dependencies.
=> [resolution pt.3] bundles and deps variable source

internal/resolution/variable_sources/bundles_and_dependencies/bundles_and_dependencies.go, internal/resolution/variable_sources/crd_constraints/crd_constraints.go, internal/resolution/variable_sources/crd_constraints/crd_constraints_test.go, internal/resolution/variable_sources/olm/olm.go, internal/resolution/variable_sources/olm/olm_test.go
This PR adds the `OLMVariableSource` which orchestrates variable creation by using the other variables sources (e.g. `RequiredPackage`, `BundlesAndDeps`, and `GlobalConstraints`)
=> [resolution pt.5] olm variable source

api/v1alpha1/operator_types.go, config/crd/bases/operators.operatorframework.io_operators.yaml, controllers/operator_controller.go, controllers/suite_test.go, internal/resolution/bundle_cache.go
This PR integrates the solver with the reconciler. It also update the Operator API to include a `BundlePath` on Operator.Status
=> [resolution pt.7] resolver integration

internal/resolution/variable_sources/utils/predicates/predicates_test.go
This PR just addresses a comment in a previous PR where a unit test description was found to be mismatched
Signed-off-by: perdasilva <perdasilva@redhat.com>
=> fixup unit test description

Makefile, config/rbac/role.yaml, controllers/operator_controller.go, controllers/suite_test.go, go.mod, go.sum, main.go, test/e2e/e2e_suite_test.go, test/e2e/install_test.go, testdata/crds/core.rukpak.io_bundledeployments.yaml
Combines @perdasilva 's latest commits with a selection from @varshaprasad96 and @ankitathomas 's [controller_prototype](https://github.com/varshaprasad96/operator-controller/tree/controller_prototype) to enable the operator-controller to create bundledeployments using a (currently hard-coded) CatalogSource. Also adds additional Makefile targets to enable simpler installation of dependencies (cert-manager and rukpak).
It should be possible to demonstrate milestone 1 by running the following two commands:
```bash
$ make run
$ kubectl apply -f config/samples/operators_v1alpha1_operator.yaml
```
=> BundleDeployment creation with BundleImage

Makefile
It looks like this should have been removed as part of the fix for #83, which seems to have already made it in in #103
=> Makefile: remove unused ENVTEST_K8S_VERSION variable

config/rbac/role.yaml, controllers/operator_controller.go
Another facet of #107 
operator-controller does not (and should not ever) need permission to create/update/patch/delete Operator objects. It needs:
- write on Operator status
- write on Operator finalizers
- read on all other operator fields
=> reduce RBAC permissions of operator-controller

controllers/operator_controller.go, go.mod
One facet of #107
Server-side apply is the preferred way to manage owned resources on a cluster. With forced ownership of the fields we care about, it give the operator controller the ability to always ensure the desired fields are set, while also allowing other controllers to manipulate fields we don't care about and that are irrelevant to the core functionality of the operator controller.
=> Use server-side apply to ensure the desired bundle deployments exist

controllers/operator_controller.go, controllers/operator_controller_test.go, controllers/suite_test.go, main.go
Another facet of #107, covering the following:
- move reconciler unit tests to a separate file from the suite. if we add other controllers in the future, we'll likely want separate test files for each controller.
- export the reconciler's resolver field to make it easy to swap out for tests (also add a test entity source)
- remove the manager setup in the unit tests. this ensures we can test individual runs of the Reconcile function, which is good for two reasons:
- no need to use Eventually, no polling, etc. so it speeds up the tests
- it ensures that we fully understand the individual transitions that occur from a beginning state to an end state when multiple Reconcile calls are necessary. (e.g. r1: create BD, r2: update Op based on BD status change to unpacking, r3: update Op again …
=> refactor and add unit tests for operator reconciler

api/v1alpha1/operator_types.go, controllers/operator_controller.go, controllers/operator_controller_test.go
This PR reduces the [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) of the `reconcile` method of the operator controller from 8 to 5 (as measured by gocyclo), mainly by factoring out the bundle entity lookup from the solution into a separate function.
It also ensures all code paths set the `Ready` condition, which required two new reasons (`BundleLookupFailed` and `BundleDeploymentFailed`)
This is built on top of #115, so
/hold
until that has merged and we've rebased this one.
=> Reduce reconcile complexity

.github/workflows/pull_request_template.md
Signed-off-by: Alexander Greene <greene.al1991@gmail.com>
=> Introduce Pull Request Template

api/v1alpha1/operator_types_test.go, api/v1alpha1/v1alpha1_suite_test.go
We currently export constants for the universe of types and reasons that the operator controller uses to set conditions. And we append them to a list that is used in reconciler tests to ensure that `Reconcile` sets each condition type during any given call. See [here](https://github.com/operator-framework/operator-controller/blob/520219c1c4812d3446c85cf8383de3572ebbbf9d/api/v1alpha1/operator_types.go#L32-L54).
However there's still a small gap. It's possible to add a new type/reason without appending it into the respective operatorutil list, which means the assumptions we make (i.e. that the operatorutil lists are exhaustive) are not enforced. And that means our invariant test for "all types must be set at the end of a reconcile call" might produce false negatives.
This PR closes that gap …
=> api: add tests that ensure types and reasons are registered correctly

.dockerignore, .github/workflows/release.yaml, .gitignore, .goreleaser.template.yml, Dockerfile, Makefile, bin/.dockerignore
Adds a release github action and implements goreleaser, borrowing heavily from rukpak but stripped down a bit.
See my fork here for an example release output: https://github.com/dtfranz/operator-controller/releases/tag/v0.0.2
Some of the additional build targets found in rukpak have been stripped out to keep this smaller.
Addresses #132 and #109
=> Operator Controller Release

controllers/operator_controller.go, controllers/operator_controller_test.go
This PR brings in the change that sets the operator condition to Unknown when the BundleDeployment's conditions are out od date.
=> Conditions: Map out-of-date bundleDeployment with an operator condition

internal/resolution/variable_sources/entity/bundle_entity.go, internal/resolution/variable_sources/entity/bundle_entity_test.go
This PR introduces the optional field while loading entities from bundles. If the property is optional and is not present, we do not error.
Fixes: #123
=> [entity_resolution] Not error when optional properties are not present in entity

.goreleaser.template.yml
=> release: build multi-arch manifest list for common platforms

.gitignore, .goreleaser.yml, Makefile, scripts/install.tpl.sh
Adds an install script which installs the required sub-components of OLM v1 in a single command. The install script is built on-the-fly when the release is run, and the appropriate versions of all sub-components are set inside the Makefile or grabbed from the go.mod file.
Addresses #110
=> Release Install script

api/v1alpha1/operator_types.go, config/crd/bases/operators.operatorframework.io_operators.yaml, config/samples/operators_v1alpha1_operator.yaml, controllers/admission_test.go, controllers/operator_controller.go, controllers/operator_controller_test.go, controllers/validators/validators.go, controllers/validators/validators_suite_test.go, controllers/validators/validators_test.go, go.mod, internal/resolution/resolver.go, internal/resolution/variable_sources/olm/olm.go, internal/resolution/variable_sources/olm/olm_test.go, internal/resolution/variable_sources/required_package/required_package.go, internal/resolution/variable_sources/required_package/required_package_test.go, main.go
Adds `.spec.version` property to the Operator CRD. Some small changes were made to the resolver and top level variable sources to accommodate for this change and, hopefully, future ones. When reviewing, we should be asking ourselves how easy it would be to add the next property.
This PR also adds a small admissions unit test, so we can validate the OpenApi validation rules we apply using the kubebuilder annotations.
I've also nerfed the stackdumps down to panic. Otherwise we just get logs pointing to internal controller-runtime code...
=> Add .spec.version

api/v1alpha1/operator_types.go, config/crd/bases/operators.operatorframework.io_operators.yaml
Just add the Channel to the API
Fixes #169
Fixes OPRUN-2916
=> Add Channel to Operator API

docs/olmv1_roadmap.md
This commit add the OLM v1 doc in markdown which is converted from the shared doc: [OLM V1 Product Requirements Document](https://docs.google.com/document/d/1-vsZ2dAODNfoHb7Nf0fbYeKDF7DUqEzS9HqgeMCvbDs/edit)
=> Convert OLM V1 MVP share doc to markdown

.github/workflows/release.yaml
The goreleaser workflow is using actions/checkout@v2 and is giving a deprecation warning, this should fix that and also bring it in-line with the other actions.
=> GitHub Checkout Action

.github/workflows/e2e.yaml, .github/workflows/go-apidiff.yaml, .github/workflows/release.yaml, .github/workflows/unit-test.yaml
Brings a bunch of our github actions back up to date to remove more deprecation warnings and also removes an unnecessary caching step since actions/setup-go@v4 does this by default.
I'll carry these changes over to rukpak as well if they work correctly :)
=> Actions Updates

.gitignore, api/v1alpha1/operator_types.go, config/crd/bases/operators.operatorframework.io_operators.yaml, controllers/admission_test.go, controllers/operator_controller_test.go, internal/resolution/variable_sources/olm/olm.go, internal/resolution/variable_sources/required_package/required_package.go
Adds backend support for channelName
Fixes #170
Fixes OPRUN-2917
=> Handle channelName

.goreleaser.yml
The quay.io/operator-framework/operator-controller images have not been built properly for multiple architectures and all manifests show as being for the amd64 arch.
This PR updates the .goreleaser.yaml file to use buildx and explicitly sets the build platform with the --platform flag.
=> update .goreleaser.yaml to properly build multi-arch images

RELEASE.md
Problem: The RELEASE.md file currently points to the operator-lifecycle-manager's release github action instead of the operator-controller's release github action.
Solution: Update the RELEASE.md document to points to the correct github action.
=> Update RELEASE.md to point to correct url

scripts/install.tpl.sh
This PR makes the `install.tpl.sh` exit on error (return code of a command != 0) to ensure that we don't try to run the e2e tests if the environment setup failed in some steps (usually kubectl_wait).
=> Fail early on e2e setup failure

Makefile
=> Makefile: don't globally export GOOS=linux

api/v1alpha1/operator_types.go, config/crd/bases/operators.operatorframework.io_operators.yaml, controllers/operator_controller.go, controllers/operator_controller_test.go, test/e2e/install_test.go
This PR extends the operator CR with a new condition: "Installed" which exposes the bundle deployment status at the operator CR level.
It also adds a new field: "installedBundleResource" that contains the installed image/git ref.
Closes #199
=> Operator CR Installed status condition

controllers/operator_controller.go
Clean-up of operator conditions with helper funcs.
Requires https://github.com/operator-framework/operator-controller/pull/218
follow-up of https://github.com/operator-framework/operator-controller/pull/218#discussion_r1200754022
=> Clean-up of operator conditions with helper funcs

api/v1alpha1/operator_types.go, api/v1alpha1/operator_types_test.go, controllers/operator_controller_test.go, internal/conditionsets/conditionsets.go
`util` is too generic for a package name.
Let's try and avoid packages like `utils`, `common`, etc as packages like this tend to become dumping grounds.
=> Removes `util` package

config/manager/manager.yaml
Add an annotation to the controller-manager manifest so that `kubectl logs <controllerManagerPod>` automatically defaults to the manager pod (not the kube-rbac-proxy pod)
=> Define default logs container for operator-controller pod

internal/resolution/variable_sources/olm/olm.go
This PR removes unnecessary constructor wrapper: `required_package.InVersionRange` and `required_package.InChannel` are no-op if inputs are empty.
=> Cleanup: removes unnecessary constructor wrapper

internal/controllers/operator_controller_test.go, internal/controllers/suite_test.go
I was reviewing #251 and noticed that there were leftover items in the envtest etcd after several operator_controller_test specs completed.
This PR:
1. Updates operator_controller_test.go to clean up after itself
2. Adds a check in AfterSuite to verify that no operators or bundle deployments remain in the cluster after all tests complete.
=> operator_controller_test: ensure we cleanup after each spec

cmd/manager/main.go, go.mod, pkg/features/features.go
- Adds a `features` package containing skeleton code for easily adding new feature gates to operator-controller
- Updates the flag parsing in `cmd/main.go` to use pflag to allow for easily adding and processing the `--feature-gates` flag
- Feature gates can be enabled/disabled by setting them with the `--feature-gates` flag like so: `--feature-gates="SomeFeature=true"
- Resolves #255
=> add feature gates infrastructure

internal/resolution/variable_sources/bundlesanddependencies/bundles_and_dependencies_test.go, internal/resolution/variable_sources/crdconstraints/crd_constraints_test.go
Follow up for #264:
* https://github.com/operator-framework/operator-controller/pull/264/files#r1235508524
* https://github.com/operator-framework/operator-controller/pull/264/files#r1235492338
=> Removes unnecessary `HaveLen` assertions

.github/workflows/unit-test.yaml
Adds integration with codecov
Closes #276
=> Adds codecov integration

config/manager/manager.yaml
=> move psa labels from deployment to namespace

test/e2e/e2e_suite_test.go, test/e2e/install_test.go
=> use env vars for possible e2e test image substitution

.github/workflows/pages.yaml, .gitignore, docs/Tasks/adding-a-catalog.md, docs/Tasks/deleting-an-operator.md, docs/Tasks/explore-available-packages.md, docs/Tasks/installing-an-operator.md, docs/components.md, docs/index.md, docs/olmv1_roadmap.md, mkdocs.yml
=> Publish /docs to github pages

.github/workflows/e2e.yaml, .github/workflows/unit-test.yaml, .gitignore, Makefile, config/e2e/kustomization.yaml, config/e2e/manager_e2e_coverage_copy_pod.yaml, config/e2e/manager_e2e_coverage_patch.yaml, config/e2e/manager_e2e_coverage_pvc.yaml, hack/e2e-coverage.sh
=> Adds E2E coverage reporting

Makefile
Currently we have `kind-cluster-cleanup` as a dependency in `kind-cluster` target. Since `make` only builds a target once this means that `e2e` target performs cleanup before creating a new cluster and skips cleanup at the end leaving cluster hanging around.
With this change, `make e2e` will be failing on cluster creation, if a cluster with the same name already exists, but the failure message will clearly indicate the issue.
=> Fixes kind cluster cleanup in `e2e` make target

.gitignore, Tiltfile, tilt.md
=> Add initial Tilt support

.github/workflows/e2e.yaml, .github/workflows/unit-test.yaml
We do not want to fail the job if codecov fails
to upload the report due to rate limiting.
=> Makes codecov-action optional

.github/workflows/e2e.yaml, .github/workflows/go-apidiff.yaml, .github/workflows/release.yaml, .github/workflows/sanity.yaml, .github/workflows/unit-test.yaml
Enable receiving `merge_group` events in preparation for enabling the merge queue.
=> Enable merge_group events

Makefile
* Fixes default target. It looks like target `all` was previously define first to implicitly set `build` to be default target, but since introduction `include` above the `all` target - now `BINGO` is default target. This change explicitly sets `build` to be default.
* Sets several targets as phony as they are not targeting a file and moves `.PHONY` closer to target definition for better visibility.
* Removes unused `wait` target
=> Tidies up `Makefile`: fixes default target, remove unused ones and makes phony targets to by be truly phony

Tiltfile
Requires https://github.com/operator-framework/tilt-support/pull/1
=> Switch to using tilt-support repo

.github/workflows/tilt.yaml
=> Add CI for tilt

Makefile
=> Delete cluster before creating op-dev-e2e test

.golangci.yaml, internal/controllers/validators/validators.go, internal/resolution/entities/bundle_entity.go, internal/resolution/entities/bundle_entity_test.go, internal/resolution/util/predicates/predicates.go, internal/resolution/util/predicates/predicates_test.go, internal/resolution/variablesources/bundles_and_dependencies.go, internal/resolution/variablesources/required_package.go
Create consistent alias for blang, enforce with golang-ci lint.
Addresses #344 in preparation for #346.
=> blang semver pkg alias

cmd/resolutioncli/entity_source.go, config/rbac/role.yaml, internal/controllers/operator_controller.go, internal/resolution/entitysources/catalogdsource.go, test/e2e/e2e_suite_test.go, test/operator-framework-e2e/operator_framework_test.go
Closes #342
This is a minimal set of changes required to switch from `BundleMetadata` API to `CatalogMetadata` and remove code duplication between resolution CLI and operator controller itself.
I expect more refactoring to be done as part of #347 where we will be removing entities/entity sources from operator controller and switching to `VariableSources`. E.g. we might want to create a wrapper for `declcfg` structs which makes it easier to traverse catalog (e.g. package might contain refs to channels and channels might contain refs to bundles). But this to be defined separately and out of scope for this PR.
The main goal of this PR is to make removal of entities and entity sources easier.
=> Switch to catalogd's `CatalogMetadata` APIs

.github/workflows/go-apidiff.yaml
go-apidiff is meant to be informational and is optional, so it will not block PRs in the merge queue, even when it finds incompatible changes. Therefore it serves no real purpose in the merge queue CI.
There also seems to be an issue with running go-apidiff in the context of a merge_queue where it fails due to invalid commit references. See https://github.com/operator-framework/operator-controller/actions/runs/6014708335/job/16315430191
For these reasons, removing it from the merge queue CI
=> Remove go-apidiff GHA from merge_group runs

config/rbac/role.yaml, internal/controllers/operator_controller.go, test/e2e/e2e_suite_test.go, test/e2e/install_test.go, test/operator-framework-e2e/operator_framework_test.go
This follows up on #343 to remove the final bits of references to the catalogd `Package` and `BundleMetadata` APIs. This is important if we want Operator Controller to be able to bump to a version of Catalogd that removes those APIs.
See https://github.com/operator-framework/catalogd/pull/149
=> Remove all references to the old catalogd Package and BundleMetadata APIs

.github/workflows/deploy.yaml, .github/workflows/e2e.yaml, Makefile
Update Makefile targets for consistency
Fixes #226
* Rename the `install` target to `kind-deploy`
* Remove `uninstall` target
* Rename the `kind-cluster-cleanup` target to `kind-clean`
* Remove the `generate` target from `kind-deploy`
* Swap `e2e`/`test-e2e` targets
* Update help descriptions
* Add `help-extended`,
* Change e2e workflow to use `test-e2e`
=> Update Makefile targets for consistency

.github/workflows/e2e.yaml, Makefile, go.mod, test/e2e/e2e_suite_test.go, test/e2e/install_test.go
Generate a summary of logs/resources after e2e runs.
- Disabled by default, to enable, pass the `ARTIFACT_PATH` env var when running the e2e tests: `ARTIFACT_PATH=/tmp/e2e/ make test`
- Enabled on GitHub CI, you can access the artifacts via the "e2e / e2e-kind (pull_request)" check/action.
Current output of a e2e test run:
```jmprusi@daedalus:/tmp/artifacts/operator-controller-e2e/1685442762094383301$ tree
.
├── argocd-operator-system
│   └── argocd-operator-controller-manager-deployment.yaml
├── catalogd-system
│   ├── catalogd-controller-manager-77b88f9f46-85hg2-kube-rbac-proxy-logs.txt
│   ├── catalogd-controller-manager-77b88f9f46-85hg2-manager-logs.txt
│   └── catalogd-controller-manager-deployment.yaml
├── cert-manager
│   ├── cert-manager-5f76f6fd49-4926c-cert-manager-logs.txt
│ …
```
=> Testing: Save pod logs and resources after e2e test run

go.mod, internal/resolution/util/predicates/predicates_test.go, internal/resolution/util/sort/sort_test.go
=> Remove ginkgo from util tests

internal/resolution/entities/bundle_entity.go, internal/resolution/entities/bundle_entity_test.go, internal/resolution/variablesources/bundles_and_dependencies.go
It doesn't look like we need this duplication.
=> Removes GVKRequired struct

internal/resolution/entities/bundle_entity.go, internal/resolution/entities/bundle_entity_test.go, internal/resolution/variablesources/bundles_and_dependencies.go
This reverts commit 5cbc9a0d5e3bbeab3ce200a9fd1da66453f0247b from #400.
We accidentally merged #400. I should’ve marked it as a draft after [this thread](https://github.com/operator-framework/operator-controller/pull/400#discussion_r1318854976).
I think both operator-registry and operator-controller can get rid of it, but it is not a trivial thing to do on operator-registry side since it uses go type to map to a property type. It is not a difficult change either, but I don’t have time to look into it at the moment.
While operator-registry still has this this extra type, I think, operator-controller should also have it. There is no impact on functionality on operator-controller side without the second type, but it might be confusing that we have two types on operator-registry side and one …
=> Revert "Removes GVKRequired struct (#400)"

internal/catalogmetadata/types.go
It is a followup to https://github.com/operator-framework/operator-controller/pull/408#discussion_r1325665653
Media type is an optional field and can be an empty string after looading. This change avoids unmarshalling every time we call MediaType() method by comparing to `nil`.
If value is `nil` - we need to load. If anything else (even an empty string) we already lazy-loaded the value.
=> Optimises `Bundle.MediaType()` (#408 follow up)

test/e2e/e2e_suite_test.go
See: https://github.com/operator-framework/operator-controller/actions/runs/6187398899/job/16797170708?pr=410
=> e2e: fix gomega assertion that breaks Eventually semantics

internal/catalogmetadata/client/client.go, internal/catalogmetadata/client/client_test.go
So we can call `client.New` instead of `client.NewClient`.
Follow up for https://github.com/operator-framework/operator-controller/pull/413/files#r1330665212
=> Renames `NewClient` to `New` to avoid duplication when imported

internal/catalogmetadata/types.go, internal/catalogmetadata/types_test.go
Moving fix from #413 into a separate PR.
=> Fixes semver range parsing for required packages

internal/controllers/operator_controller_test.go, test/e2e/install_test.go, testdata/catalogs/test-catalog/catalog.yaml
#413 fixed the bug described in #419
This PR updates tests to ensure there are no regressions.
=> fix: do not include channel name or priority in bundle sorting during resolution

api/v1alpha1/operator_types.go, config/crd/bases/operators.operatorframework.io_operators.yaml
=> Add `upgradeConstraintPolicy` field to `Operator` spec

codecov.yml
Currently we have 2 jobs that report code coverage to codecov. This setting makes codecov to wait for both before sending notifications such as comments and pull request checks.
=> Make codecov wait for both jobs to upload coverage

internal/resolution/variables/bundle.go
Subj. Follow up for https://github.com/operator-framework/operator-controller/pull/453#discussion_r1355622226
=> Rename variable to avoid shadowing

internal/resolution/variablesources/bundle_deployment.go, internal/resolution/variablesources/bundles_and_dependencies.go
Switches from `map` of empty `struct`s to using sets package from apimachinery utils.
Note: there is also `internal/resolution/variablesources/crd_constraints.go` which uses map for empty structs, but there is #461 which modifies this file and makes use of sets package.
Fixes #454
=> Add k8s.io/apimachinery/pkg/util/sets

internal/controllers/operator_controller_test.go
Different packages in the test data were sharing the same channel. It doesn't currently affect the test, but in real world this doesn't happen since channel belongs to only one package
Also there was a bit strange formatting of bundle structs.
=> Fix and re-format test data

internal/resolution/variablesources/crd_constraints.go, internal/resolution/variablesources/crd_constraints_test.go
Partly addresses #459. I would still want to keep the issue open so we can get rid of `prettyUnsatMessage` function.
=> Remove randomness in package uniqueness ordering

Makefile, internal/resolution/variablesources/installed_package.go, internal/resolution/variablesources/installed_package_test.go, test/e2e/install_test.go, testdata/catalogs/test-catalog/catalog.yaml
OLM will now use SemVer to determine next upgrade. In this iteration we only support upgrade within the same major versions: e.g 1.0.1 can be upgraded to 1.0.2 or 1.3.2, but not 2.0.0.
Closes #398
=> Add initial SemVer upgrade support

internal/resolution/variablesources/installed_package_test.go
Zero major version is reserved for initial development according to [SemVer spec](https://semver.org/#spec-item-4) and anything may change at any time.
As the result of the above update behaviour is different for it.
This is a follow up for https://github.com/operator-framework/operator-controller/pull/444#discussion_r1364836753
=> Add extra tests for zero major version

internal/controllers/suite_test.go
This will enable both Ginkgo and standard Go tests to use the same setup & teardown.
This will help to get rid of some of the setup boilerplate in #469.
=> Refactor controllers test setup & teardown for reusability between Ginkgo and standard Go tests

internal/controllers/operator_controller_test.go
Adds `OperatorReconciler` reconcile tests for `Operator` upgrades. Tests include:
* Upgrade tests with semver upgrade constraints
* Upgrade tests with legacy OLMv0 upgrade constraints
Closes #468
=> `Operator` update tests with semver and legacy upgrade constraints

internal/resolution/variablesources/installed_package.go, internal/resolution/variablesources/installed_package_test.go
=> Fix filtering of successors bundles

test/operator-framework-e2e/operator_framework_test.go
Zero major version is reserved for initial development according to SemVer spec[^1] and anything may change at any time.
Updates for this version behaves differently:
* When version is `0.1.0` we allow versions which are >= `0.1.0` and < `0.2.0` (patch updates)
* When version is `0.0.1` we allow versions which are >= `0.0.1` and < `0.0.2` (no updates)
To be able to update in the second case (e.g. from `0.0.1` to `0.0.2`) users will have to set `.spec.upgradeConstraintPolicy` to `Ignore` once support for this implemented.
We have unit tests for the above behaviour, but E2E test data was not updated.
[^1]: https://semver.org/#spec-item-4
Fixes #481
=> Update E2E test data to fix `operator-developer-e2e`

internal/controllers/operator_controller.go
=> 🐛 use correct context for catalog watch handler

.github/dependabot.yml, .github/pull_request_template.md, .github/workflows/pr-title.yaml
Update PR template to provide guidance on title icons.
Add job to verify icon in PR title.
Make sure dependabot PRs titles are prefixed with :seedling:.
=> 🌱 PRs: use icons in descriptions

internal/resolution/variablesources/bundle.go, internal/resolution/variablesources/bundle_test.go
Follow up for https://github.com/operator-framework/operator-controller/pull/498#discussion_r1381696321
=> 🌱 Improve error message about missing bundles

internal/resolution/variablesources/bundle_deployment.go, internal/resolution/variablesources/installed_package.go, internal/resolution/variablesources/installed_package_test.go
Spliting https://github.com/operator-framework/operator-controller/pull/460 into smaller chunks. Related to https://github.com/operator-framework/operator-controller/issues/437
In this part I extract code related to creating installed package variables from `InstalledPackageVariableSource` and `BundleDeploymentVariableSource` into a separate function.
`InstalledPackageVariableSource` gets removed in this PR. `BundleDeploymentVariableSource` will be removed later in #501
=> 🌱 Part 3: Reduce number of variable sources. Installed packages

internal/resolution/variablesources/bundle_deployment_test.go, internal/resolution/variablesources/installed_package.go, internal/resolution/variablesources/installed_package_test.go
Follow up for https://github.com/operator-framework/operator-controller/pull/499#discussion_r1381994273
=> 🌱 Improve installed package error when bundle can not be found

internal/resolution/variablesources/bundle_deployment_test.go, internal/resolution/variablesources/installed_package_test.go
The code we test relies on UID and having UID set will ensure greater correctness of our tests.
=> 🌱 Add UID to fake `Operator` objects in tests

internal/catalogmetadata/cache/cache.go, internal/catalogmetadata/cache/cache_test.go
- Updates the field used for identifying whether or not the cache of `Catalog` contents is stale
- resolves #528
=> 🐛 update catalog status field being used for stale cache identification

internal/resolution/variablesources/bundle_deployment_test.go, internal/resolution/variablesources/installed_package.go, internal/resolution/variablesources/installed_package_test.go
This commit adds extra bundle filtering when looking for a currently installed bundle. This prevents updates
from one package to another in case when currently installed bundle shares bundle image with a bundle from another package.
Closes #466
=> 🐛 Prevent updates from one package to another

test/e2e/e2e_suite_test.go, test/e2e/install_test.go
This removes dependency between tests and prevents cascading failures
Closes #512
=> 🐛 Remove dependency between tests and prevent cascading failures

internal/controllers/operator_controller.go
We already have a version which contains the fix and can revert to a simpler check.
=> 🐛 Resolve Deppy error check todo

internal/resolution/variablesources/bundle_deployment_test.go, internal/resolution/variablesources/fake_object_utils_test.go, internal/resolution/variablesources/installed_package_test.go
This commit does two things.
First: It splits the `TestMakeInstalledPackageVariables` test into two tests:
* One for when `ForceSemverUpgradeConstraints` feature gate enabled (semver)
* One for when `ForceSemverUpgradeConstraints` feature gate disabled (legacy semantics)
Both tests are now table-style tests.
This is done mainly so that we can maintain test data for different semantics separately (e.g. no need to maintain channel entires for semver tests).
Second: Adds extra coverage for disabled state of the `ForceSemverUpgradeConstraints` feature gate. Previously we were not covering some cases for this state of the gate. Example of such case is when `UpgradeConstraintPolicy` field on `Operator` is set to `Ignore`.
=> 🌱 Update installed package unit tests

test/e2e/install_test.go
=> 🐛 Wait for catalog deletion before recreation

internal/controllers/operator_controller.go, internal/controllers/operator_controller_test.go, test/e2e/install_test.go
It was a workaround a Deppy issue. We no longer need it since Deppy fixed the issue.
Related Deppy issues:
* https://github.com/operator-framework/deppy/issues/150 
* https://github.com/operator-framework/deppy/issues/142
Closes #459
=> 🌱 Remove `prettyUnsatMessage` workaround

internal/controllers/admission_test.go, internal/controllers/operator_controller_test.go, internal/controllers/suite_test.go
Fix #190
This also puts back some of the post-testing cleanup.
=> :seedling: Remove ginkgo from internal/controller unit tests

Makefile, go.mod, go.sum, test/e2e/e2e_suite_test.go, test/e2e/install_test.go, test/operator-framework-e2e/operator_framework_test.go, test/operator-framework-e2e/setup.sh
=> :seedling: Remove ginkgo from e2e tests

go.mod, go.sum, internal/controllers/operator_controller_test.go, internal/controllers/variable_source_test.go, internal/resolution/variablesources/fake_object_utils_test.go, internal/resolution/variablesources/installed_package.go
Bumping rukpak dependency to v0.16.0. This includes changes to the way that rukpak names `Bundle` objects derived from `BundleDeployments` and the way that performs registry+v1 to plain conversion. This results in different names and labels for some objects, so it may be a breaking change for some users.
=> ⚠ bump rukpak to v0.16.0

docs/drafts/upgrade-support.md
Draft document to cover initial upgrade support.
Closes #470
=> 📖 Draft documentation for initial upgrade support

api/v1alpha1/clusterextension_types.go, cmd/resolutioncli/client.go, internal/catalogmetadata/client/client.go, internal/catalogmetadata/client/client_test.go, internal/catalogmetadata/filter/bundle_predicates.go, internal/catalogmetadata/filter/bundle_predicates_test.go, internal/catalogmetadata/sort/sort.go, internal/catalogmetadata/sort/sort_test.go, internal/catalogmetadata/types.go, internal/catalogmetadata/types_test.go, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_controller_test.go, internal/resolution/variablesources/required_package.go, internal/resolution/variablesources/required_package_test.go, test/e2e/install_test.go
- Add new condition types and reasons to signal when an installed bundle for a `ClusterExtension` has deprecations associated with it
- Update the `catalogmetadata.Bundle` type to have fields to hold the deprecation information for a bundle
- Update the resolution logic to prefer bundles with deprecations less than bundles without
- Update the `ClusterExtension` reconciler logic to add the deprecation statuses if there are any associated with the installed bundle
- Implements [RFC: OLMv1 Graph Deprecation](https://docs.google.com/document/d/1CYGANKILfzfOoWtHvyg4luF7i-cC1NRa7_1N9xTLatw/edit?usp=sharing)
- fixes #525 
- fixes #526 
- fixes #527
=> :sparkles: (feat): add graph deprecation logic

.bingo/Variables.mk, .bingo/variables.env, Makefile, go.mod, go.sum
- Bumps catalogd --> v0.11.0
- Bumps kind to v0.20.0 and ensures we are using a 1.28 node image for testing
=> :seedling: bump catalogd to v0.11.0

internal/catalogmetadata/sort/sort_test.go, internal/catalogmetadata/types.go, internal/catalogmetadata/types_test.go, internal/controllers/clusterextension_controller.go
- Updates the `catalogmetadata.Bundle.IsDeprecated()` method to no longer return true if there is a package deprecation associated with the bundle
- Adds unit tests for the `catalogmetadata.Bundle.IsDeprecated()` method
=> :seedling: don't consider bundle deprecated if the package is deprecated

.github/dependabot.yml
Python dependabot PRs such as #576 are not being prefixed. This PR adds a enw configuration for pip package-ecosystem.
=> 🌱 Prefix dependabot pip PRs

config/e2e/manager_e2e_coverage_copy_pod.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_client_clusterrole.yaml, config/rbac/auth_proxy_role.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/auth_proxy_service.yaml, config/rbac/clusterextension_editor_role.yaml, config/rbac/clusterextension_viewer_role.yaml, config/rbac/kustomization.yaml, config/rbac/leader_election_role.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml, config/samples/olm_v1alpha1_clusterextension.yaml, internal/controllers/clusterextension_controller.go, internal/controllers/extension_controller.go
=> ✨ kustomize: remove extraneous labels and rules, include editor/viewer roles

api/v1alpha1/extension_types.go, config/crd/bases/olm.operatorframework.io_extensions.yaml, internal/controllers/extension_admission_test.go, internal/controllers/extension_controller_test.go
=> ✨ extension: use union discriminator patther in source specification

api/v1alpha1/extension_types.go, config/crd/bases/olm.operatorframework.io_extensions.yaml, internal/controllers/extension_controller.go, internal/controllers/extension_controller_test.go
=> ✨ extension: spec.managed (enum) => spec.paused (bool), add status.paused

Makefile, scripts/install.tpl.sh
Adds [kapp-controller ](https://github.com/carvel-dev/kapp-controller) to the install script and pins version to `v0.50.0`. Left a comment to note that once we add `kapp` to `go.mod` we can retrieve the version from there, so we have the version in just one place.
Closes #609
=> 🌱 Add kapp-controller to Makefile to be installed with "run" command.

cmd/manager/main.go
The method was listing resources falling under the `kappctrl.k14s.io` string. It would return nil when kapp-ctrl is not installed, resulting in a panic.
=>  🐛 [Fix] fix hasKappAPIs method

docs/Tasks/explore-available-packages.md, docs/refs/catalog-queries.md, mkdocs.yml
* https://github.com/operator-framework/operator-controller/issues/693
* Add a _copy_ button for code blocks and support for admonitions
* Add "Catalog queries" and reference documentation directory
* Update and rename "Finding extensions to install"
* References > [Catalog queries](https://deploy-preview-696--olmv1.netlify.app/refs/catalog-queries/)
* Tasks > [Finding extensions to install](https://deploy-preview-696--olmv1.netlify.app/tasks/explore-available-packages/)
=> :book: Update documentation for "Finding extensions to install"

docs/Tasks/installing-an-extension.md, docs/Tasks/uninstall-an-extension.md, docs/refs/catalog-queries.md
* Issue https://github.com/operator-framework/operator-controller/issues/693
* Update "Installing an extension"
* I will add links to more information about version ranges, comparison strings, in follow up PRs
* Update "Deleting an extension"
* [Installing an extension](https://deploy-preview-700--olmv1.netlify.app/tasks/installing-an-extension/)
* [Deleting an extension](https://deploy-preview-700--olmv1.netlify.app/tasks/uninstall-an-extension/)
=> :book: Update docs for Installing and deleting extensions

Makefile
Grabs the kapp version from what we are currently using in go.mod in order to ensure parity.
=> 🌱 Source Makefile kapp version from go.mod

.github/workflows/e2e.yaml
- Removes the `-k` option from the `make` command run to execute our e2e tests in CI. The `-k` flag would force `make` to continue running a target even when a dependency of the target has failed leading to flakes. Removing the flag means that the e2e tests will fail if any of the `test-e2e` target dependencies fail.
=> 🌱 Update e2e action to reduce flakes

README.md, docs/olmv1_overview.md
=> 📖 Add OLMv1 Overview doc

Makefile, api/v1alpha1/extension_types.go, config/crd/bases/olm.operatorframework.io_extensions.yaml
Adds an optional `Extension.spec.skipCRDUpgradeSafetyChecks` field that when set to `true` will be used to disable the CRD upgrade safety checks when attempting to install an extension.
No logic included in this PR as the CRD Upgrade Safety preflight check hasn't been fully implemented in carvel-dev/kapp yet.
I figured it doesn't hurt to go ahead and add the field and have it do nothing for now, but I'm also happy for this PR to be put on hold until the underlying logic to enable/disable the check is able to be put in place.
fixes #658
=> :sparkles: Add field to Extension API to skip crd safety checks

docs/Tasks/explore-available-packages.md, docs/refs/catalog-queries.md
Closes https://github.com/operator-framework/operator-controller/issues/698
* Fix codeblocks in the Catalog queries description list
* Fix typos that were called out after PR https://github.com/operator-framework/operator-controller/pull/696 was merged
* [Catalog queries](https://deploy-preview-728--olmv1.netlify.app/refs/catalog-queries/) (better formatting and the *copy* button at the end of the code block)
* Finding extensions to install (fix typos)
=> 📖 Fix jq codeblocks

README.md
Just a few spelling, formatting, and punctuation updates for the README.
=> 📖 README: formatting and spelling fixes

config/manager/manager.yaml, internal/catalogmetadata/filter/bundle_predicates.go, internal/catalogmetadata/filter/bundle_predicates_test.go, internal/controllers/common_controller.go, internal/resolution/variablesources/installed_package.go, internal/resolution/variablesources/installed_package_test.go, test/e2e/cluster_extension_install_test.go
=> ✨use legacy successors, support skips and skipRange

cmd/manager/main.go, internal/catalogmetadata/filter/bundle_predicates.go, internal/catalogmetadata/filter/bundle_predicates_test.go, internal/controllers/extension_controller.go, internal/controllers/extension_controller_test.go, internal/controllers/suite_test.go, testdata/crds/kappctrl.k14s.io_app.yaml
Adds an annotation to the App created for each extension indicating the bundle version, which can then be used on future reconciles to filter out older versions. This can be overridden by setting the Extension's `UpgradeConstraintPolicy` to `Ignore`.
Closes #654 
This PR borrows a lot of stuff from @varshaprasad96 's PR #690 so I've added her as co-author :)
=> ✨ Filter out bundle versions lower than installed

go.mod, go.sum, internal/controllers/clusterextension_controller.go, internal/controllers/suite_test.go, internal/rukpak/api/bundle_types.go, internal/rukpak/convert/registryv1.go, internal/rukpak/operator-registry/registry.go, internal/rukpak/source/common.go, internal/rukpak/source/image.go, internal/rukpak/source/unpacker.go, internal/rukpak/util/hash.go, internal/rukpak/util/labels.go, internal/rukpak/util/util.go
=> :sparkles: Starting Helm POC - pull in some rukpak

internal/catalogmetadata/filter/bundle_predicates.go, internal/catalogmetadata/filter/bundle_predicates_test.go, internal/controllers/extension_controller.go, internal/controllers/extension_controller_test.go
With the current code there are a few issues:
1. `catalogfilter.HigherBundleVersion` is not really required as we already have more generic `catalogfilter.InMastermindsSemverRange`.
1. I think `catalogfilter.HigherBundleVersion` allows upgrades from one major version to another major version, etc. This is not the same behaviour as in `ClusterExtension`
1. We do not seem to support legacy `replaces` here.
This PR solves the first two, but the third still needs to be addressed.
How it currently works in `ClusterExtension`: https://github.com/operator-framework/operator-controller/blob/52cb7eb1a650731f2e16253a7f0f0ba25ea3af70/docs/drafts/upgrade-support.md
=> ⚠️ (Partially) fix upgrade behaviour in `Extension`

api/v1alpha1/clusterextension_types.go, cmd/manager/main.go, go.mod, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_status.go, internal/rukpak/handler/interfaces.go, internal/rukpak/handler/registry.go, internal/rukpak/storage/localdir.go, internal/rukpak/storage/storage.go, internal/rukpak/util/fs.go, internal/rukpak/util/util.go
=> ✨ Plug in unpacker, add Handler

api/v1alpha1/clusterextension_types.go, cmd/manager/main.go, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_status.go, internal/rukpak/storage/localdir.go, internal/rukpak/util/tar.go, internal/rukpak/util/util.go
=> :warning: A bit of cleanup

api/v1alpha1/clusterextension_types.go, internal/controllers/clusterextension_controller.go, internal/controllers/common_controller.go, internal/rukpak/helm-operator-plugins/predicate/depedent.go
=> :warning: Install the helm chart

internal/controllers/clusterextension_controller.go, internal/rukpak/handler/registry.go, internal/rukpak/util/labels.go
I don't think there is need to list helm releases, to find metadata. The helm install code, in the `getReleaseState` method does comparison of the templated and existing chart and finds if changes are needed. 
Additionally, based on the [documentation](https://helm.sh/docs/topics/advanced/#storage-backends), helm by default creates and manages secrets for each release, and if we want pass any additional sensitive data to the chart, we need to do so while templating. Which means, we can use the default release which the helm creates and store bundle version and name through annotations in the chart.
=> ✨ Set up right watches and all labels to postrenderer

api/v1alpha1/clusterextension_types.go, cmd/manager/main.go, internal/controllers/clusterextension_controller.go, internal/controllers/suite_test.go
=> :warning: Deal with panics during unit test

Makefile, kind-config.yaml
We will be using [validating admission policy](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/) API for a few things (like https://github.com/operator-framework/operator-controller/issues/736) and [enforcing package uniqueness](https://github.com/operator-framework/operator-controller/pull/758#issuecomment-2066688215) on `ClusterExtension`).
This PR enables `admissionregistration.k8s.io/v1beta1` in kind cluster used for E2E and local development.
=> 🌱 Enable `admissionregistration.k8s.io/v1beta1`

config/rbac/role.yaml, internal/controllers/clusterextension_controller.go
=> ✨ Add relevant RBAC to enable controller to watch resources

Makefile
* We do not seem to use `FOCUS` and `E2E_FLAGS` in `Makefile`
* Remove envtest from e2e targets
=> 🌱 Cleanup `Makefile`

.github/workflows/tilt.yaml
We already have kind cluster setup scripted in `Makefile` which includes correct configuration.
=> 🌱 GitHub Actions: Setup kind cluster without ctlptl

config/admission/admission.yaml, config/admission/kustomization.yaml, config/admission/kustomizeconfig.yaml, config/default/kustomization.yaml
To enforce package uniqueness across `ClusterExtension`.
We currently have this enforcement on the operator-controller level, but with Deppy removal in #758 we want to shift it into API server.
=> ✨ Add `ValidatingAdmissionPolicy` to enforce package uniqueness across `ClusterExtension`

Makefile
Seems like one instance of CONTAINER_RUNTIME was missed so that it still was not possible to choose the container runtime for `make docker-build`
=> 🐛 Replace one last CONTAINER_RUNTIME in make

test/e2e/cluster_extension_admission_test.go
=> 🌱 Add `ClusterExtension` package uniqueness test

cmd/manager/main.go, internal/catalogmetadata/client/client_test.go, internal/controllers/suite_test.go, internal/controllers/variables_test.go, pkg/scheme/scheme.go, test/e2e/e2e_suite_test.go
This PR adds a scheme package providing a central location for new apis to be added to scheme.
Also replaces the use of a new scheme instance and var by importing the package scheme and using scheme.Scheme.
Solves #322
=> ✨ ADD scheme package for AddToScheme

Makefile
Rather than change XDG_DATA_HOME, since many distributions do not explicitly define XDG_DATA_HOME but rather fallback to the default, use a new optional variable SETUP_ENVTEST_BIN_DIR to override the setup_envtest binary directory.
Setting XDG_DATA_HOME in the Makefile was breaking the kind cluster setup on Fedora which just uses the default fallback value for XDG_DATA_HOME.
=> 🐛 Use bin-dir override on setup_envtest

test/e2e/cluster_extension_admission_test.go
Deals with a flake such as this:
```
go test -tags upstream -v ./test/e2e/...
=== RUN   TestClusterExtensionPackageUniqueness
cluster_extension_admission_test.go:30: create first resource
cluster_extension_admission_test.go:42: create second resource with the same package as the first resource
cluster_extension_admission_test.go:54: create second resource with different package
cluster_extension_admission_test.go:66: update second resource with package which already exists on the cluster
cluster_extension_admission_test.go:69: 
Error Trace:	/home/runner/work/operator-controller/operator-controller/test/e2e/cluster_extension_admission_test.go:69
Error:      	Error "Operation cannot be fulfilled on clusterextensions.olm.operatorframework.io \"test-extension-74hdj\": the object has been …
```
=> 🌱 Use server side apply to update test resource

docs/requirements.txt, requirements.txt
Merges dependabot PRs: #787 and #773
=> :seedling: Bump mkdocs to 1.6.0 and mkdocs-material to 9.5.19

Makefile
Optional `--bin-dir` was passed incorrectly.
=> 🐛 Fix envtest `--bin-dir`

Tiltfile, internal/controllers/clusterextension_controller.go
- Set installed and resolved version in CE status.
- Remove rukpak from tilt.
=> ✨ Set resolved and installed versions

Makefile
The podman-specific kind-load commands in the Makefile currently write the image archive to a temporary file named $IM but that by default includes slashes and a colon. My changes replace any slashes or colons with hyphens to prevent any errors trying to write that file.
Also, the naming doesn't really matter, we can just make it be a hard-coded "tmp.tar" or something.
Also, also, I saw the closed PR from earlier today and the discussion about not getting too into the weeds on podman/docker-specific configuration in the Makefile, but the current setup will cause that file-write error for anyone who does use CONTAINER_RUNTIME=podman with our default env variables, so I figured that was worth a quick fix.
=> 🐛 Sanitize temporary filename for podman image load

Makefile
=> :sparkles: Add make kind-redeploy

config/e2e/manager_e2e_coverage_copy_pod.yaml, config/manager/manager.yaml
=> 🐛 use FallbackToLogsOnError termination message policy

internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_registryv1_validation_test.go
Draft for the changes proposed in [this doc](https://docs.google.com/document/d/1Bwhv00KtFfB5JQ_11JAN00YnyehzGPIyYb3mdnc9GxM/edit): disallowing registry+v1 bundles with dependencies.
Closes #779
=> ⚠️ Disallow bundles with dependencies and constraints

.goreleaser.yml, Makefile
I was experiencing extreme delays in running `make` for any target so finally decided to run it through `strace` to see what I could find. It turns out `make` was evaluating almost all of our variables many many times due to the use of `=` and `?=` instead of `:=`.
See https://www.gnu.org/software/make/manual/html_node/Flavors.html#Flavors for docs about the various flavors of variables.
While I was at it, I also cleaned up and improved a few other things:
- Auto-detect docker, fallback to podman, fail if neither are present
- Remove GO_BUILD_TAGS. The original intention was to have a way to inject extra or different code in other distributions of operator-controller. We've seen Red Hat's OCP distribution use carry patches in a fork instead.
- Remove unused or minimally useful variables. …
=> 🌱 Makefile: fix issues with repeated evaluations, other minor improvements

cmd/manager/main.go, internal/controllers/clusterextension_controller.go, internal/controllers/suite_test.go
=> 🌱 Remove `Scheme` from `ClusterExtensionReconciler`

Makefile
E2E targets do not depend on envtest as they use a real kind cluster.
=> 🌱 No SETUP_ENVTEST target is required for E2E

internal/controllers/clusterextension_controller.go
Due to the polling feature in the Catalog, the `lastPolledInterval` in the Catalog's status gets updated. Because of this there is a reconcile triggered every time the catalog is polled, even though there is no change in the resolved image ref.
This causes unnecessary continuous reconciles in the CE reconciler. To overcome this, a Predicate is added to accept update events only when there is a change in Resolved image reference in catalog's status.
=> :bug: [Fix] Constant reconciles due to Catalog's poll interval

api/v1alpha1/clusterextension_types.go, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_status.go, internal/controllers/common_controller.go
=> :sparkles: Fix linter

Dockerfile, Makefile, cmd/manager/main.go, cmd/unpack/main.go, config/manager/kustomization.yaml, config/manager/manager.yaml, go.mod, go.sum
Builds and loads the unpacker binary into the operator-controller image so we don't need to use the rukpak image.
=> ✨ Helm poc unpack image

Makefile, cmd/manager/main.go, internal/version/version.go
- resolves #328 
- this just adds git commit version for now. Do we want to also show the release version?
=> :sparkles: Add version flag for operator-controller manager binary

go.mod, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_controller_test.go, internal/controllers/clusterextension_registryv1_validation_test.go
Fixes several ClusterExtension controller related unit tests. Not ones related to cache not being started though.
=> ✨ OPRUN-3293 Fixes several unit tests - not cache ones 

Makefile, test/e2e/cluster_extension_registryV1_limitations_test.go, testdata/bundles/registry-v1/package-with-webhooks.v1.0.0/Dockerfile, testdata/bundles/registry-v1/package-with-webhooks.v1.0.0/manifests/bundle-with-webhooks.clusterserviceversion.yaml, testdata/bundles/registry-v1/package-with-webhooks.v1.0.0/metadata/annotations.yaml, testdata/catalogs/test-catalog/catalog.yaml
No bundles with webhooks are currently allowed and we must be clearly indicated in the conditions of `ClusterExtension`.
Closes #815
=> ✨ Add test to verify registry+v1 webhooks limitation

Makefile
when unable to find docker or podman as this evaluation results in an error in environments where docker or podman is not installed even when using targets that do not require a container runtime
- Updates the `CONTAINER_TOOL` evaluation logic to warn instead of error out when `docker` or `podman` are not detected in the path. This makes it so that in environments where neither is installed, running targets that don't require a container runtime can still be run. A caveat is that the targets needing a container runtime will still attempt to run and fail. I believe issuing a warning is a good middle ground to provide a clear reason why a target that requires a container runtime would fail, but am open to suggestions on better ways to approach this.
=> 🌱 Update CONTAINER_TOOL evaluation in makefile to warn instead of error

docs/drafts/upgrade-support.md
Update the doc to reflect the current default state of upgrade constraint semantics
Related to #744
=> 📖 Correct docs about the default upgrade constraint semantics

api/v1alpha1/clusterextension_types.go, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_controller_test.go, test/e2e/cluster_extension_install_test.go
=> ✨ Cleanups

internal/catalogmetadata/filter/bundle_predicates.go, internal/catalogmetadata/filter/bundle_predicates_test.go, internal/controllers/clusterextension_controller.go, test/e2e/cluster_extension_install_test.go, test/e2e/cluster_extension_registryV1_limitations_test.go
Fixes the e2e tests in helm-poc branch.
=> 🌱 Helm POC e2e fixes

dev/podman/kind-with-registry-podman.sh, dev/podman/setup-local-env-podman.md
Adding a helper script for a podman-based kind cluster with an image registry.
This should help local testing by speeding up initial setup, required for running Tilt.
=> ✨ Helper script for a podman kind cluster with an image registry

cmd/manager/main.go, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_controller_test.go, internal/controllers/clusterextension_registryv1_validation_test.go, internal/controllers/suite_test.go
Follow on to the helm-poc changes:
We'd like to not have a global variable for `GetInstalledBundle`, but instead an easier to test interface.
=> 🌱 Change global var GetInstalledBundle to interface

internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_controller_test.go, internal/controllers/common_controller.go
=> :sparkles: Use error type rather than strings

api/v1alpha1/clusterextension_types.go, internal/controllers/clusterextension_controller.go, internal/controllers/common_controller.go, test/e2e/cluster_extension_install_test.go
Remove references to rukpak k8s API where possible.
With the removal of Extension, the status update functions no longer need to be generic. Simplify the function signatures
This also makes the update functions consistent signature/behavior.
=> :sparkles: Update status update functions

Makefile, testdata/catalogs/test-catalog/catalog.yaml
To allow access to the docker-registry certificate, move the e2e resources into the same namespace as the operator-controller-system namespace.
=> :sparkles: Move the e2e into the operator-controler-system ns

cmd/manager/main.go, internal/catalogmetadata/filter/bundle_predicates.go, internal/catalogmetadata/filter/bundle_predicates_test.go, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_controller_test.go, internal/controllers/clusterextension_registryv1_validation_test.go, internal/controllers/successors.go, internal/controllers/successors_test.go, internal/controllers/suite_test.go
The installed bundle provider, which is necessary for safely handling package upgrades, was too strict. It required the currently installed bundle to exist in the catalog in order to "find" the installed bundle.
This is problematic in several  situations:
- If a user receives a catalog update that no longer contains their installed bundle (perhaps its was removed from the catalog for security or policy reasons)
- If a user is trying to transition to a different catalog that provides that package
- If a bundle was directly installed, and the user is trying to have a catalog-backed ClusterExtension adopt it.
This change simply returns the name and version of the installed bundle, and makes some minor changes in the successors functions to handle the simplified installed bundle metadata.
=> 🐛 Fix: installed bundle provider no longer requires catalog

Makefile, testdata/catalogs/test-catalog/catalog.yaml
This ends up overwriting the security policy of the operator-controller-system namespace, which really isn't something we want to do in a valid e2e test.
Many of the e2e components need to run as root in order to do the things they need to do.
This reverts commit aa48e704bbbc4ae808fff5e3d762f95df3a0982a.
=> :bug: Revert "Move the e2e into the operator-controler-system ns"

Makefile, dev/podman/kind-with-registry-podman.sh, kind-config.yaml
We no longer need to enable `ValidatingAdmissionPolicy` since it is enabled by default in K8s 1.30.
This means we can delete `kind-config.yaml`.
=> 🌱 Remove kind config

Makefile
It looks like #888 we moved rbac manifests, but did not update controller-gen output path. This PR should fix this.
=> 🐛 Fix rbac generation in `Makefile`

README.md
=> 🌱 mac setup steps

cmd/manager/main.go, config/base/rbac/role.yaml, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_registryv1_validation_test.go, internal/controllers/suite_test.go, test/e2e/cluster_extension_install_test.go
=> ✨ remove unnecessary flag, optimize catalog watch handler, stop watching non-existent unpack pods

.github/workflows/e2e.yaml, .github/workflows/unit-test.yaml
* `functionalities` param is no longer exist. It was used to enable file fixes to ignore common lines from coverage. This feature is now seems to be on by default.
* Adding `disable_search` because we do not need for the codecov action to search for coverage files: we explicitly provide files.
This solves:
* Gets rid of "Warning: Unexpected input(s) 'functionalities'" warning.
* Excludes yaml files from coverage report uploaded to codecov.
=> 🌱 Fix codecov-action params

cmd/manager/main.go, internal/controllers/clusterextension_controller.go
Our cache configuration resulted in watching all cluster-scoped resources for each cluster-scoped resource that shows up in a ClusterExtension. Now, we only watch:
- All ClusterExtensions
- All ClusterCatalogs
- All objects in the systemNamespace
- All other objects that specifically match the dependentPredicate
This commit also removes the dependent predicate so that we reconcile for any change to managed resources. This is important to ensure that future features (like health checking) can account for any change to managed operator objects.
=> 🐛 fix: reduce unnecessary caching and remove predicate from dynamic watches

cmd/manager/main.go, config/base/manager/manager.yaml
When I removed the flag that controlled the bundle cache root directory in #941, I missed the fact that we also had a volumeMount for it, which is a child of our broader `/var/cache` volume emptyDir volume.
This commit eliminates the unnecessary extra volume and instead just creates the `/var/cache/bundles` directory in the existing volume.
This is important to eliminate the potential for issues when attempting to rename files across filesystem boundaries using `os.Rename` (e.g. if we ever needed to do something like  rename `/var/cache/tmp/foobar.txt` to `/var/cache/bundles/foobar.txt`)
=> 🐛 fix: remove unnecessary bundle cache volume

api/v1alpha1/clusterextension_types.go, config/base/crd/bases/olm.operatorframework.io_clusterextensions.yaml
Make `spec.installNamespace` immutable.
Fixes #961
=> 🐛 fix: make installNamespace immutable

internal/controllers/clusterextension_controller_test.go
Cover what happens when we fail to fetch bundles from catalog.
This should solve flaky test coverage. It looks like in E2E we sometimes are hitting this condition and sometimes we don't which results in coverage fluctuation:
=> 🌱 Add test for fetching bundles

Makefile, internal/catalogmetadata/cache/cache.go, internal/catalogmetadata/cache/cache_test.go, internal/catalogmetadata/client/client.go, internal/catalogmetadata/client/client_test.go, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_controller_test.go, internal/controllers/clusterextension_registryv1_validation_test.go, internal/controllers/common_controller.go, internal/controllers/suite_test.go, internal/testutil/fake_catalog_client.go
This partially resolves #914 by doing two things:
1. Exploding the `all.json` response into separate directories organized by package
2. Updating the BundleProvider to require a package name to be provided in the request, which results in a much smaller set of FBC that needs to be re-parsed into catalogmetadata objects on each reconcile.
This is still not completely resolved though because step (1) still happens synchronously during the reconciliation of a ClusterExtension. In order to finish the improvement (and to complete #948), we need to implement a controller that watches and reconciles ClusterCatalog changes so that it can create (and delete) caches for operator-controller.
=> 🐛 incremental improvement in catalogmetadata cache/client performance

Makefile
Fixes issues with golang caching during e2e tests.
=> :seedling: Add -count=1 to local e2e tests to avoid caching

internal/controllers/clusterextension_controller.go
We'll use the default exponential backoff behavior
Fix #882
=> :seedling: Remove comment about retries.

api/v1alpha1/clusterextension_types.go, internal/controllers/clusterextension_controller.go, internal/controllers/common_controller.go, test/e2e/cluster_extension_install_test.go
Closes #989 by removing the condition and solves an E2E flake.
Note: in [this brief](https://docs.google.com/document/d/1JWJxnDXM0X1JQ67ZIDx5j1ayb1d7ajrK_uSDDaz0G98/edit) were are revisiting `ClusterExtension` conditions and their reasons. [One of the points](https://docs.google.com/document/d/1JWJxnDXM0X1JQ67ZIDx5j1ayb1d7ajrK_uSDDaz0G98/edit#heading=h.l1ogecrfxz55) is about removal of `HasValidBundle` condition type.
The brief is still in review, but I would like to move forward with this change as it resolves a flake I hit regularly (especially locally).
=> ⚠️ Remove `HasValidBundle` condition

internal/authentication/tokengetter.go, internal/authentication/tokengetter_test.go
As part of #737 user provided service accounts will be used to manage cluster extensions, the token getter implemented in this PR enables this by providing an interface to fetch tokens given a service account. It also implements a cache where fetched tokens are stored saving requests to the api server for subsequent requests. Fixes #972
=> ✨ Adding a token getter to get service account tokens

internal/authentication/tokengetter.go, internal/authentication/tokengetter_test.go
Fixes for some issues that were over looked in #1006 including:
- Fixed unintentional integer division when rotating tokens
- Fixed populating TokenRequest.Spec with nanoseconds instead of seconds
- Removing the parameter that controls the duration after which expired tokens should be deleted and instead deleting them as soon as they are encountered
=> ✨ Fixes and Improvements for TokenGetter

Makefile, kind-config.yaml, test/tools/image-registry.sh
- expose a nodeport on kind cluster
- change image registry service to portforward on port 30000
- add image repository name for all catalog images
=> ✨ expose a nodeport on kind cluster

cmd/manager/main.go, go.mod, go.sum, internal/controllers/clusterextension_controller.go
This PR bumps to a new version of helm-operator-plugins, which brings a few new fixes, features, and changes. Notably:
- ActionClientGetter: allow disabling rollbacks after failures 
This PR also:
- makes use of the new ActionClientGetter knob so that operator-controller no longer rolls back a failed install or upgrade.
- sets a max version history of 10 to avoid unlimited piling up of release secrets
- uses helm's new server-side dry-run option, which provides cluster information to helm templates (e.g. when using the `lookup` template function).
For all changes, see https://github.com/operator-framework/helm-operator-plugins/releases/tag/v0.3.0
Closes #994
=> ✨ bump helm-operator-plugins to v0.3.0; disable failure rollbacks

Makefile
This target is broken because `OPERATOR_CONTROLLER_NAMESPACE` does not exist.
=> 🌱 Remove `kind-redeploy` make target

.github/workflows/e2e.yaml, Makefile, hack/pre-upgrade-setup.sh, test/upgrade-e2e/post_upgrade_test.go, test/upgrade-e2e/upgrade_e2e_suite_test.go
Testing upgrade from the latest release to the current commit.
Fixes #856
=> ✨ Add upgrade E2E

.github/workflows/e2e.yaml, .github/workflows/unit-test.yaml, Makefile, hack/e2e-coverage.sh
Move:
- `./e2e-cover.out` -> `./coverage/e2e.out`
- `./cover.out` -> `./coverage/unit.out`
Add Go 1.20+ gocoverdirs
- `./coverage/e2e`
- `./coverage/unit`
=> 🌱 consolidate and save all coverage data under ./coverage

internal/controllers/clusterextension_controller.go, test/upgrade-e2e/post_upgrade_test.go
After the upgrade, make sure reconcile actually completes for the ClusterExtension before we being the post-upgrade checks and tests.
=> 🌱 upgrade test: wait until first reconcile completes after upgrade

test/upgrade-e2e/post_upgrade_test.go
Example failure is [here](https://github.com/operator-framework/operator-controller/actions/runs/9941062379/job/27459241132?pr=1047):
```
go test -count=1 -v ./test/upgrade-e2e/...
=== RUN   TestClusterExtensionAfterOLMUpgrade
post_upgrade_test.go:27: Starting checks after OLM upgrade
post_upgrade_test.go:32: Checking that the controller-manager deployment is updated
post_upgrade_test.go:48: Waiting for only one controller-manager Pod to remain
post_upgrade_test.go:54: Reading logs to make sure that ClusterExtension was reconciled by operator-controller before we update it
post_upgrade_test.go:66: Checking that the ClusterCatalog is unpacked
post_upgrade_test.go:78: Checking that the ClusterExtension is installed
panic: runtime error: invalid memory address or nil pointer dereference …
```
=> 🐛 Fix nil pointer dereference in upgrade E2E

cmd/manager/main.go, internal/controllers/clusterextension_controller.go, internal/httputil/httputil.go, internal/rukpak/bundledeployment/bundledeployment.go, internal/rukpak/source/image_registry.go
=> :sparkles: Use x509.CertPools instead of PEM strings

test/e2e/cluster_extension_install_test.go, test/e2e/e2e_suite_test.go
- adds a new e2e test to check whether the Operator-controller resolves to updated the installed bundle version when the clusterCatalog image is patched.
=> ✨ add new e2e test - TestClusterExtensionInstallReResolvesWhenCatalogIsPatched

cmd/manager/main.go, internal/action/error/errors.go, internal/action/error/errors_test.go, internal/action/helm.go, internal/action/helm_test.go
As part of #736 we'd like to mark helm errors when an installation fails due to conflict. This PR wraps the ActionClient interface we use to talk to helm and processes the errors returned give a set of programatic rules. So far, only the install conflict error translator is modeled
=> :sparkles: mask helm conflict errors

go.mod
This will be required for us to bump kapp which requires 1.22.5 and [currently fails](https://github.com/operator-framework/operator-controller/pull/1063):
```
Error: load packages in root "/home/runner/work/operator-controller/operator-controller": err: exit status 1: stderr: go: carvel.dev/kapp@v0.63.2 requires go >= 1.22.5 (running go 1.22.0)
```
=> 🌱 Bump go to 1.22.5

.github/dependabot.yml
This should help group k8s dependencies into a single PR when possible.
Relevant doc: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
=> 🌱 Add dependabot K8s dependencies group

cmd/manager/main.go, config/base/rbac/role.yaml, config/samples/olm_v1alpha1_clusterextension.yaml, hack/test/pre-upgrade-setup.sh, internal/controllers/clusterextension_controller.go, test/e2e/cluster_extension_install_test.go, test/extension-developer-e2e/extension_developer_test.go
#973 Add functionality to use Service Account
=> :sparkles: Wire up Service Account

api/v1alpha1/clusterextension_types.go, config/base/crd/bases/olm.operatorframework.io_clusterextensions.yaml, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_controller_test.go, internal/controllers/common_controller.go
Cleaner Condition Types & Reasons. See commit messages for coverage of this PR and its sync to the RFC recommendations. https://docs.google.com/document/d/1JWJxnDXM0X1JQ67ZIDx5j1ayb1d7ajrK_uSDDaz0G98
=> ✨ Cleaner Condition Types & Reasons

cmd/manager/main.go, config/base/rbac/role.yaml, hack/test/pre-upgrade-setup.sh, internal/authentication/tokengetter.go, internal/authentication/tripper.go, internal/contentmanager/contentmanager.go, internal/controllers/clusterextension_controller.go, test/e2e/cluster_extension_install_test.go, test/extension-developer-e2e/extension_developer_test.go
- Updates the RestConfigMapper to use a new `TokenTripper` that wraps a `http.RoundTripper` to always set the Authorization header to the referenced ServiceAccount
- Updates the E2E ServiceAccounts introduced in #1038 to use a scoped set of permissions instead of giving it cluster-admin equivalent permissions (used `bind` + `escalate` for RBAC to keep the SA permissions as succinct as possible. Open to changing this if desired)
- Updates the `ClusterExtensionReconciler` to have an exported field that can be used to configure the `contentmanager.Watcher` that should be used to establish watches on the ClusterExtension managed objects
- Updates the `contentmanager.Instance.Watch()` method to create watches with the same configurations as existed in the …
=> :sparkles: wire up ServiceAccount based caching layer

Makefile, scripts/install.tpl.sh
Addresses #1026 by adding OperatorHub to the default installation script.
Installs default-catalogs.yaml from Catalogd release.
=> ✨ Install default-catalogs.yaml from Catalogd release

internal/controllers/clusterextension_controller.go
Removes old conditional for handling ErrReleaseNotFound which was preventing the new logic from firing.
=> 🐛 Bug: remove old conditional in ClusterExtension

cmd/manager/main.go, config/base/rbac/role.yaml, config/base/rbac/role_binding.yaml, config/samples/olm_v1alpha1_clusterextension.yaml, go.mod, go.sum, internal/action/restconfig.go, internal/action/storagedriver.go, internal/controllers/clusterextension_controller.go
This PR:
1. uses a new helm release storage driver from `helm-operator-plugins` that chunks release data into one or more secrets (this also incidentally means that our client and the Helm CLI client won't mistake each other's release storage for their own).
2. moves release secret storage back to our system namespace so that we don't leak details of our release bookkeeping to users.
3. Notes that the new helm-operator-plugins commit also makes it possible to use one service account for release storage and a separate service account for deploying bundle contents. This is necessary if we want to avoid leaking our internal release storage mechanism to users (who would otherwise have to configure RBAC for release storage permission)
Fixes: …
=> ⚠️ helm: use chunking release driver in systemNamespace

internal/labels/labels.go
=> 🐛 labels: use consistent format for keys

docs/Tasks/installing-an-extension.md, docs/refs/crd-upgrade-safety.md, mkdocs.yml
=> 📖 Add CRD Upgrade Safety documentation

config/samples/catalogd_operatorcatalog.yaml, config/samples/olm_v1alpha1_clusterextension.yaml
- Remove  * / * / * permissions in argocd clusterextension installer RBAC
- Set sample catalog polling to `10m` to match what is installed in the install script.
=> ✨samples: polling and RBAC improvements

config/samples/olm_v1alpha1_clusterextension.yaml, docs/drafts/permissions-for-owner-references-permission-enforcement-plugin.md, kind-config.yaml, test/e2e/cluster_extension_install_test.go, test/extension-developer-e2e/extension_developer_test.go
Kubernetes has many admission policy plugins that are disabled by default when using vanilla Kubernetes. Vendors of Kubernetes tend to enable the `OwnerReferencesPermissionEnforcement` plugin. One prominent example of a vendor enabling this plugin is OpenShift.
In order to ensure OLM works seamlessly on as many Kubernetes distributions as possible, we should enable this plugin in our kind config.
=> 🌱 enable OwnerReferencesPermissionEnforcement in project kind config

config/base/manager/manager.yaml, config/base/prometheus/monitor.yaml, config/base/rbac/auth_proxy_service.yaml, test/upgrade-e2e/post_upgrade_test.go
As the label selector used for both catalogd and operator-controller metrics services is "control-plane: controller-manager". Hence changing the labels in both operator-controller and catalogd to make sure we do not overlap.
=> :bug:  Fixing the labels for better  metrics collection

hack/test/pre-upgrade-setup.sh
The default kind config for e2e was updated with `OwnerReferencesPermissionEnforcement` and the setup script for the `upgrade-e2e` test was missing the required permissions on the installer clusterrole. This adds the required fields as detailed in our docs.
=> 🐛: Fix ClusterExtension Finalizer RBAC for upgrade-e2e

docs/index.md, docs/olmv1_overview.md
=> 📖  update general/product documentation

api/v1alpha1/clusterextension_types.go, config/base/crd/bases/olm.operatorframework.io_clusterextensions.yaml
=> ✨ update ClusterExtension.Spec.PakageName to be immutable

api/v1alpha1/clusterextension_types.go, config/base/crd/bases/olm.operatorframework.io_clusterextensions.yaml, internal/applier/helm.go
=> ✨ convert field CRDUpgradeSafetyPolicy to be an enum

.github/workflows/tilt.yaml
Fixes tilt not using declared catalogd version in go.mod file, causing the ci to fail if catalogd is updated in an incompatible way (i.e. API change).
=> 🐛: Fix tilt ci

api/v1alpha1/clusterextension_types.go, config/base/crd/bases/olm.operatorframework.io_clusterextensions.yaml
Updates the GoDoc comments in the `ClusterExtension` API to be more user readable, user the JSON field name in references, and ensures all optional fields are marked with the `//+optional` comment tag
- Fixes #1147 
- Fixes #1144 
- Fixes #1143
=> :book: Update GoDoc comments for the `ClusterExtension` API

internal/resolve/catalog.go, internal/resolve/catalog_test.go, test/e2e/cluster_extension_install_test.go, test/e2e/e2e_suite_test.go
Fix #1112
Adds some tests to validate the label selector.
Modified some tests to add labels and selectors. They are not necessary now, but will be once 1110 is resolved; as that issue adds the ambiguity that this PR helps resolve.
=> :sparkles: Add in catalog label selection support

internal/resolve/catalog.go, internal/resolve/catalog_test.go, test/e2e/cluster_extension_install_test.go
Changes the behavior of catalog resolution by returning an error when multiple packages are available from multiple catalogs. 
Users will need to use forthcoming label selectors to narrow down catalogs when this occurs.
Closes #1110
=> ⚠: Ambiguous Resolution

internal/rukpak/source/image_registry_test.go, internal/rukpak/util/hash_test.go, internal/rukpak/util/util_test.go
Adds more tests to the packages migrated from rukpak.
Closes #1037
=> 🌱 Internal Rukpak Package Tests

internal/resolve/catalog.go, internal/resolve/catalog_test.go
We initially assumed that the resolvedBundle index we check doesn't matter when it comes to checking for prior package deprecations in the resolver but the index needs to match the prior result or the bundle names may not match and give a false negative.
Also improved the unit test cases (which caught the above issue).
=> 🐛: Improve Catalog Selection Testing + Fix small issue

config/base/rbac/role.yaml, config/samples/catalogd_operatorcatalog.yaml, docs/Tasks/adding-a-catalog.md, go.mod, go.sum, hack/test/pre-upgrade-setup.sh, internal/controllers/clusterextension_controller.go
Alternative to #1172
This has a new API path (olm... vs catalogd...)
Update all references to catalogd.operatorframework.io
This _will_ fail the upgrade-e2e, since it depends on the "latest" version of operator-controller, which does not reference the correct API path.
Once this is merged, then subsequent upgrade-e2e's will pass.
=> :warning: Update to catalogd v0.21.0

go.mod, go.sum, internal/resolve/catalog.go, internal/resolve/catalog_test.go
Fixes: #1117 
Lots of changes to the catalog test infrastructure, as I needed to include information about the catalog itself.
=> :sparkles: Use a catalog's priority to as a bundle selection tie-breaker

internal/rukpak/preflights/crdupgradesafety/checks.go, internal/rukpak/preflights/crdupgradesafety/crdupgradesafety.go, internal/rukpak/preflights/crdupgradesafety/crdupgradesafety_test.go, testdata/manifests/crd-conversion-no-webhook.json, testdata/manifests/crd-conversion-webhook-old.json, testdata/manifests/crd-conversion-webhook.json, testdata/manifests/crd-field-removed.json, testdata/manifests/crd-valid-upgrade.json, testdata/manifests/old-crd.json
New preflight check that checks for either the presence of the "Webhook" conversion strategy to pass, or checks for any incompatible changes between served versions in the new CRD which, if found, causes failure..
Closes #1091
Adds a new preflight check, ServedVersionValidator, which checks for breaking changes between served versions in the new CRD when upgrading.
Happy to change up any naming or error messages.
Existing test data had to be edited so it wouldn't trigger the new check--the empty v1 in all the test data has just been filled in to match the test data v2.
=> ✨ Add ServedVersionValidator preflight check

internal/resolve/catalog_test.go
Both catalogs should have a package available for the label selector to really demonstrate that it picks one of two catalogs
=> :bug: Update test

cmd/manager/main.go
We can get object's name without type casting.
=> 🌱 Remove unnecessary type casting in the finaliser

internal/catalogmetadata/cache/cache.go
There is a bug in the optimisation where we try to avoid writing, if another thread already updated the cache: I believe we should be checking `catalog.Status.ResolvedSource.Image.ResolvedRef` (includes sha) as in other places instead of `catalog.Status.ResolvedSource.Image.Ref`.
Related:
* #529
* #528
=> 🐛 Fix cache check

internal/rukpak/convert/registryv1.go, internal/rukpak/convert/registryv1_test.go
This is needed for the cluster olm operator to find the ocp max version
=> :sparkles: feat:  dump csv annotations into chart metadata

internal/catalogmetadata/client/client.go
Small change to update doc comment to reflect the current reality
=> 🌱 Fix doc comment

cmd/manager/main.go, internal/controllers/clusterextension_controller.go
Moving finaliser key to a constant instead of dynamically generating it. We do it the same way [in catalod](https://github.com/operator-framework/catalogd/blob/4a6f3160f5b809325f5b8747db5c250ac93ef837/internal/controllers/core/clustercatalog_controller.go#L43). Another finalisers will be added in #1207 in a similar way.
=> 🌱 Define a constant for the finaliser key

api/v1alpha1/clusterextension_types.go, config/base/crd/bases/olm.operatorframework.io_clusterextensions.yaml, internal/controllers/clusterextension_admission_test.go
- Updates existing field comments and validations to adhere more closely to Kubernetes naming conventions
- Resolves #1149
=> :warning: update name validation patterns to match Kubernetes as close as possible

docs/drafts/upgrade-support.md
Closes #744
@perdasilva: I am not sure if you are using this file as part of your work. I just wanted to make sure we aren't stepping on each other's toes :)
=> 📖 [Docs] Add support for skip ranges and replacements

docs/drafts/how-to-version-range-upgrades.md
=> 📖 [Docs] How-to: Version Range Automatic Updates

docs/drafts/how-to-z-stream-upgrades.md
=> :book:[Docs] How-to: Z-stream Automatic Updates

docs/drafts/how-to-pin-version.md
=> :book:[Docs] How-to: Pin Version and Disable Automatic Updates

docs/drafts/how-to-channel-based-upgrades.md
=> :book:[Docs] How-to: Channel-Based Automatic Updates

go.mod, go.sum, internal/resolve/catalog_test.go, scripts/install.tpl.sh, test/e2e/cluster_extension_install_test.go, test/e2e/e2e_suite_test.go
Fix #1115
* Use proper labels from catalogd
* Add better deployment checking
* Fix broken test
This test seems broken, it's supposed to resolve again after updating to V2. The test implies that this should be the 2.0.0 version, but it's checking against 1.2.0 (which was the original version installed).
=> :seedling: Update to catalogd v0.26.0 and update e2e tests

api/v1alpha1/clusterextension_types.go, config/base/crd/bases/olm.operatorframework.io_clusterextensions.yaml, docs/refs/api/operator-controller-api-reference.md
Fixes https://github.com/operator-framework/operator-controller/issues/1146
Replaces #1171
=> ⚠️ types conversions from review

tilt.md
=> 📖 [Docs] Document tilt-support install

docs/drafts/provided-serviceaccount.md
=> 📖 Add provided ServiceAccount documentation to drafts

docs/Tasks/installing-an-extension.md, docs/refs/supported-extensions.md, mkdocs.yml
Closes #984
Direct link to the rendered preview:
* [Supported extensions](https://deploy-preview-1263--olmv1.netlify.app/concepts/supported-extensions/)
=> 📖 [Docs] Supported extensions (OLM v1 constraints/limitations)

docs/drafts/single-owner-objects.md
=> 📖 [Docs] Single ClusterExtension ownership concept

.github/workflows/go-verdiff.yaml, Makefile, hack/tools/check-go-version.sh
=> :seedling: Add CI to check if golang version updated

Makefile, config/components/registries-conf/registries_conf_configmap.yaml, hack/test/image-registry.sh, test/e2e/cluster_extension_install_test.go, testdata/catalogs/test-catalog-v1/catalog.yaml
This PR is intended to (partially) resolve issues around the complexity of implementing an e2e test that proves `/etc/containers/registries.conf` is honored.
It:
- puts everything back to a registry with a trusted cert across the board
- changes `registries.conf` in the standard e2e to map from a "mirrored-registry" to "docker-registry"
- adds a new package in the shared catalog called "prometheus-mirrored" whose bundle ref uses the "mirror-registry" domain
- updates the `ClusterExtensionInstallRegistry` e2e test to verify installs of both "prometheus" and the new "prometheus-mirrored" package (the latter would fail without the mapping config)
=> 🌱 switch back to use of trusted CA, add extra test for mirror registry

internal/rukpak/source/containers_image.go, internal/rukpak/source/containers_image_test.go, internal/rukpak/source/unpacker.go
=> ✨ use controller-runtime Terminal error instead of our custom Unrecoverable error

internal/catalogmetadata/cache/cache_test.go
We do not want to modify `http.DefaultClient` because it can cause undesired effects in other places.
=> 🌱 Fix `http.DefaultClient`

internal/controllers/clusterextension_controller.go
This is a fix for a bug that @anik120 stumbled upon in catalogd while working on https://github.com/operator-framework/catalogd/pull/379.
Wanted to fix it here as well while we're thinking about it.
=> 🐛 fix: do not silently drop finalizer updates when status is also updated

docs/drafts/developer.md
Reordered sections and added MacOS setup into a dedicated section. Improved structure for better readability and provided clear instructions for installing and using necessary tools.
=> 📖 [Docs] Reorganize developer documentation

docs/Tasks/adding-a-catalog.md, go.mod, go.sum, hack/tools/catalogs/download-catalog, internal/catalogmetadata/client/client.go, internal/catalogmetadata/client/client_test.go, scripts/install.tpl.sh, test/e2e/cluster_extension_install_test.go, test/upgrade-e2e/post_upgrade_test.go
=> 🌱 Bump catalogd from v0.28.0 to v0.29.0

api/v1alpha1/clusterextension_types.go, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_controller_test.go
=> :warning: Removing healthy status condition

docs/components.md, docs/drafts/architecture.md
The documentation contains description of the components and a diagram. Removed the components.md file as the architecture doc contains the same information
Fixes : [#1124](https://github.com/operator-framework/operator-controller/issues/1124)
=> :book: Adding OLM V1 architecture document

api/v1alpha1/clusterextension_types.go, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_controller_test.go, internal/controllers/common_controller.go, internal/controllers/common_controller_test.go, internal/rukpak/source/unpacker.go, test/e2e/cluster_extension_install_test.go
- Adds a new `Progressing` status condition
- Removes unpack states that we never expect to be returned from our implementation, makes reconciliation panic if we get an unexpected state since it is a programmer error
- Consolidates some unit tests
- fixes #1292
=> ✨ add progressing condition

api/v1alpha1/clusterextension_types.go, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_controller_test.go, internal/controllers/common_controller.go, test/e2e/cluster_extension_install_test.go
This PR removes the "Unpacked" status which has now been rolled into a "Progressing" status. 
Fixes #1294
=> ✨ Remove unpacked status

cmd/manager/main.go
=> ✨ Use creds if present for pulling bundle images

api/v1alpha1/clusterextension_types.go, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_controller_test.go, internal/controllers/common_controller.go, test/e2e/cluster_extension_install_test.go
=> ✨ Remove the Resolved status condition

cmd/manager/main.go
=> 🐛 main.go: improve logging for configuration of global auth

cmd/manager/main.go, config/base/manager/manager.yaml, go.mod, internal/controllers/clusterextension_controller.go, test/upgrade-e2e/post_upgrade_test.go
Use standard klog now that klog works with controller-runtime's expectation of a logr.Logger interface. 
We get a standard --v flag and we are more in line with k8s standards. 
We also get client-go and other low-level logging from k8s libraries at the higher verbosity levels which could be immensely helpful for debugging.
See similar PR in catalogd: https://github.com/operator-framework/catalogd/pull/419
=> ✨main.go: switch to klog-based logger

cmd/manager/main.go, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_controller_test.go, internal/finalizers/finalizers.go
Updates Installed status condition per status condition RFC. Closes #1291.
=> ✨ Update Installed status condition handling

internal/contentmanager/source/dynamicsource.go, internal/contentmanager/source/dynamicsource_test.go
Also decreasing 1 second poll interval to 100ms. The `HasSynced` check that repeats every interval simply locks mutexes and checks variables available in memory, so it is extremely fast and has low over head. This decreased the test's average time from >1000ms to ~250ms
=> 🐛 dynamicsource: fix race condition with wait and valid scheme

test/e2e/cluster_extension_install_test.go
When `require` assertions are not satisfied they fails a test immediately. This is not desired when used
with retry function such as `EventuallyWithT` since they are supposed to retry on a failure.
This can cause flakes when, for example, we are asserting on a resource condition. On the first hit the resource might not have a condition and `require` will fail `EventuallyWithT` despite the fact that the code is correct and the condition gets set eventually.
Example failures from today & yesterday:
* https://github.com/operator-framework/operator-controller/actions/runs/11123906109/job/30908338221
* https://github.com/operator-framework/operator-controller/actions/runs/11145592682/job/30975544168
* https://github.com/operator-framework/operator-controller/actions/runs/11147969636/job/3098353 …
=> 🌱 Flakes: replace `require` with `assert` in retry funcs

cmd/manager/main.go, internal/catalogmetadata/cache/cache.go, internal/catalogmetadata/cache/cache_test.go, internal/catalogmetadata/client/client.go, internal/catalogmetadata/client/client_test.go
It is now possible to cache errors occured on the cache population. This will be useful when we start proactively populating cache from `ClusterCatalogReconciler` instead of doing this on-demand.
This refactoring also moves the responsibility of performing network requests out of the cache backend into the client.
This is done in preparation for #1284
=> 🌱 Refactor `catalogmetadata` client and cache

.golangci.yaml, internal/action/helm_test.go, internal/catalogmetadata/cache/cache_test.go, internal/catalogmetadata/client/client_test.go, internal/catalogmetadata/filter/bundle_predicates_test.go, internal/catalogmetadata/filter/successors_test.go, internal/controllers/clusterextension_controller_test.go, internal/resolve/catalog_test.go, internal/rukpak/source/containers_image_test.go, test/e2e/cluster_extension_install_test.go
While reviewing https://github.com/operator-framework/operator-controller/pull/1330 we had a discussion about the ability to generally prevent the use of `requires` within `Eventually` calls to prevent future flakes, and that led us to evaluate the `testifylint`-er to give us some cautionary guidelines.  It did _not_ resolve the requires-within-eventually issue, but we may try to tackle that with some custom AST in the future.
=> ✨ add testify linter and address fixes

test/upgrade-e2e/post_upgrade_test.go
There is a potential for nil pointer dereference in the test. This change adds condition to check for nil.
Example failures:
* https://github.com/operator-framework/operator-controller/actions/runs/11168271140/job/31046293874?pr=1284
=> ✨ Fix a flake in upgrade e2e

config/samples/catalogd_operatorcatalog.yaml, docs/api-reference/catalogd-api-reference.md, docs/concepts/controlling-catalog-selection.md, docs/getting-started/olmv1_getting_started.md, docs/tutorials/add-catalog.md, docs/tutorials/install-extension.md, go.mod, go.sum, hack/tools/catalogs/README.md, hack/tools/catalogs/download-catalog, internal/catalogmetadata/cache/cache.go, internal/catalogmetadata/client/client.go, internal/catalogmetadata/client/client_test.go, internal/controllers/clusterextension_controller.go, test/upgrade-e2e/post_upgrade_test.go
=> 🌱 bump catalogd to v0.30.0

hack/test/pre-upgrade-setup.sh
=> 🐛 pre-upgrade-setup.sh: use updated ClusterCatalog API

docs/project/public-api.md
mkdocs build was reporting some broken links in the public-api page. This fixes them up =D
=> :book: fix public api links

cmd/manager/main.go, internal/controllers/pull_secret_controller.go, internal/controllers/pull_secret_controller_test.go, internal/rukpak/source/containers_image.go, internal/rukpak/source/containers_image_test.go
RFC: https://docs.google.com/document/d/1BXD6kj5zXHcGiqvJOikU2xs8kV26TPnzEKp6n7TKD4M/edit#heading=h.x3tfh25grvnv
=> ✨ Add PullSecret controller to save pull secret data locally

internal/controllers/clusterextension_controller.go
Fix #1296 
Don't allow an update to occur when the deployment is still installing.
=> :sparkles: Add checks for helm deployment status

docs/index.md, docs/project/olmv1_architecture.md, docs/project/olmv1_limitations.md, docs/project/olmv1_roadmap.md
I asked ChatGPT to do some language polishing, and did some of my own XD
=> :book: documentation touch-ups

docs/howto/derive-service-account.md
Fix a typo for a link ref in the doc (derive-service-account.md)
=> 📖 Fix typo for a link ref in derive-service-account.md

internal/rukpak/source/containers_image.go
This fixes "pushing signatures for OCI images is not supported" error when working with signed source images.
If policy context requires signature validation for a registry we will still be performing it on pull, but we will be removing source signatures when copying into a temporary OCI layout for unpacking.
=> 🐛 Fix pulling signed images

go.mod, go.sum
=> 🌱 Bump catalogd to v0.32.0

docs/howto/catalog-queries.md
=> 🐛 Fix a missing apostrophe in docs

.github/workflows/release.yaml
Addresses usage of deprecated goreleaser flags
=> :seedling: Address goreleaser deprecated flags

internal/rukpak/source/containers_image.go
Fixes a bug where we always pulled image references using the canonical reference. Now we pull images using the reference provided to the source. Using only the canonical reference resulted in not respecting some mirroring configurations related to tags because we never used tag-based references.
=> 🐛  Use provided imgRef instead of always using canonical ref in containers image source

docs/api-reference/catalogd-api-reference.md, docs/api-reference/catalogd-webserver.md, docs/howto/catalog-queries.md, docs/tutorials/add-catalog.md, docs/tutorials/explore-available-content.md, go.mod, go.sum, hack/tools/catalogs/download-catalog, internal/catalogmetadata/client/client.go, internal/catalogmetadata/client/client_test.go
see
[catalogd v0.34.0 release notes](https://github.com/operator-framework/catalogd/releases/tag/v0.34.0) for more details
=> ⚠️ updated to use catalogd v0.34.0

go.mod, go.sum
Just one bug fix in this one: https://github.com/operator-framework/catalogd/releases/tag/v0.35.0
=> 🐛 bump to catalogd v0.35.0

scripts/install.tpl.sh
There have been a number of test and CI failures due to cert-manager not being ready. This adds additional checks to the deployments and specifically to the mutating webhook configuration.
=> :seedling: Make sure cert-manager is ready

go.mod, go.sum, internal/action/helm.go, internal/action/helm_test.go, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_controller_test.go, internal/controllers/common_controller.go, internal/controllers/suite_test.go, internal/labels/labels.go, test/e2e/cluster_extension_install_test.go
=> :sparkles: Use Helm List operator to determine Deployed status

scripts/install.tpl.sh
=> :sparkles: Fix a typo in the catalogs installation step

cmd/manager/main.go, internal/catalogmetadata/client/client.go, internal/catalogmetadata/client/client_test.go, internal/controllers/clustercatalog_controller.go, internal/controllers/clustercatalog_controller_test.go
Currently we fetch catalog data and populate cache on demand during `ClusterExtension` reconciliation. This works but the first reconciliation after `ClusterCatalog` creation or update is slow due to the need to fetch data.
With this change we proactively populate cache on `ClusterCatalog` creation and check if cache needs to be updated on `ClusterCatalog` update.
=> ✨ Populate/update cache on ClusterCatalog reconcile

api/v1alpha1/clusterextension_types.go, config/base/crd/bases/olm.operatorframework.io_clusterextensions.yaml
Unless we add another `.status` field, this is what we can do. Only simple queries starting with `.` can be used.
Alternative to: #1019 
Resolves #1018
=> :sparkles: Add support for kubectl printer columns

codecov.yml
- Updated .codecov.yml to include only specific directories (api/, cmd/, internal/) in coverage reports
- Excluded documentation, YAML configurations, and test files to improve coverage accuracy and prevent irrelevant CI coverage failures
Example: 
The PR https://github.com/operator-framework/operator-controller/pull/1430 just add docs and should not fail with but it is:
=> 🌱 (chore): configure Codecov to include only relevant directories for coverage

CONTRIBUTING.md
- Added steps for building, loading Docker images, and deploying changes locally with Kind
=> 📖 docs: add local build and deploy instructions to CONTRIBUTING.md

docs/concepts/controlling-catalog-selection.md, docs/getting-started/olmv1_getting_started.md
Replace `apiVersion: catalogd.operatorframework.io/v1alpha1` with `apiVersion: olm.operatorframework.io/v1alpha1` for `clustercatalogs.olm.operatorframework.io`.
Reason:
The API version referenced in the docs appears incorrect. After installing, the correct API name is confirmed with:
```
$ kubectl get crds | grep clustercatalog
clustercatalogs.olm.operatorframework.io   2024-11-06T21:34:38Z
```
The API is listed under `clustercatalogs.olm.operatorframework.io`, not `catalogd`.
Example error faced when trying to apply with the incorrect API name:
```
$ kubectl apply -f - <<EOF
> apiVersion: catalogd.operatorframework.io/v1alpha1
> kind: ClusterCatalog
> metadata:
>   name: operatorhubio
> spec:
>   source:
>     type: Image
>     image:
>       ref: quay.io/operatorhubio/catalog:latest
> …
```
=> 📖  fix(docs): fix apiVersion for clustercatalogs. Replace 'catalogd.operatorframework.io/v1alpha1' with 'olm.operatorframework.io/v1alpha1'

scripts/install.tpl.sh
BY running `make kind-deploy` against a kind cluster  or installing the released script from https://operator-framework.github.io/operator-controller/getting-started/olmv1_getting_started/ the following error is faced:
```sh
...
deployment.apps/cert-manager-webhook condition met
deployment.apps/cert-manager-cainjector condition met
deployment.apps/cert-manager condition met
error: jsonpath wait format must be --for=jsonpath='{.status.readyReplicas}'=3
```
This PR fixes an issue with kubectl wait when used to check the caBundle field in `mutatingwebhookconfigurations` and `validatingwebhookconfigurations`. 
This PR introduces the `kubectl_wait_for_query` function, which replaces `kubectl wait` for this specific use case. The function repeatedly checks the `caBundle` field by using `kubectl …
=> 🐛 fix: resolve JSONPath error in caBundle readiness check by adding kubectl_wait_for_query function

test/e2e/cluster_extension_install_test.go, test/e2e/e2e_suite_test.go
Fixes #1307
Create and use a new namespace for every e2e test. This means that extension resources are placed in their own namespace. The tests deletes the namespace, and then waits until completion. This ensures that _most_ of an extension's resources are deleted.
It does guarantee that global resources (e.g. CRDs, CRs, CRBs) are deleted.
And would eventually allow the tests to be run in parallel (assuming the installed extensions allow for that).
=> :sparkles: Use a separate namespace for each e2e test

internal/rukpak/convert/registryv1.go, internal/rukpak/convert/registryv1_test.go
=> 🐛 fix: put annotations in deployment's pod template

config/samples/catalogd_operatorcatalog.yaml, hack/test/pre-upgrade-setup.sh
There were several intentional breaking changes in the API which are now included in v0.18.0 release.
Our upgrade-e2e job need to be updated to make take the changes into account.
Relevant PRs:
* https://github.com/operator-framework/operator-controller/pull/1439
* https://github.com/operator-framework/operator-controller/pull/1434
=> 🌱 Fix upgrade-e2e CI job

api/v1/groupversion_info.go, config/samples/kustomization.yaml, docs/api-reference/operator-controller-api-reference.md, docs/getting-started/olmv1_getting_started.md, docs/howto/derive-service-account.md
There are a few remaining references to v1alpha1 that need to be updated to use v1.
Ref:
* https://github.com/operator-framework/operator-controller/pull/1228
=> 🐛 Update remaining v1alpha1 references with v1

CONTRIBUTING.md, docs/concepts/controlling-catalog-selection.md, docs/concepts/upgrade-support.md, docs/contribute/developer.md, docs/getting-started/olmv1_getting_started.md, docs/howto/catalog-queries.md, docs/howto/derive-service-account.md, docs/tutorials/downgrade-extension.md, docs/tutorials/explore-available-content.md, docs/tutorials/upgrade-extension.md
Fixes a number of formatting/rendering issues. Mostly around lists, admonitions (notes, warnings, etc) and collapsible text.
> [!TIP]
> Recommend reviewing the changes with `git diff --ignore-all-space` (`-w`) option. GitHub UI also has this option.
>  ![Screenshot 2024-11-12 at 15 59 15](https://github.com/user-attachments/assets/d4c123d8-d6fb-4007-9e01-d4fbfed2e4d6)
> [!TIP]
> We also have docs deployment preview. See the comment from netlify bot below.
=> 📖 Improve formatting on the docs website

docs/howto/catalog-queries.md
This commit adds definition lists for placeholders such as `<package_name>`. The goal of adding definition lists for placeholders is to improve their visibility in the code snippets.
This commit also switches existing definition lists [1] (list of queries) to unordered list. The current list of queries uses definition lists from mkdocs-material. However it relies on a tailing space after a colon to work. E.g. the whole line becomes `: ` and it is prone to errors because:
1. It is easy to overlook a space which is part of markdown.
2. Many editors remove tailing spaces at the end of lines.
3. We are adding more definition lists into this docs to explain placeholders such as `<package_name>`. With nested definition lists markdown of this document going to be very difficult to manage.
[1]: …
=> 📖 Change formatting in the "Catalog queries" doc

docs/concepts/version-ranges.md
Currently this document renders fine on GitHub, but the table is broken in mkdocs website.
> [!TIP]
> We also have docs deployment preview. See the comment from netlify bot below.
> See: [this PR](https://deploy-preview-1462--olmv1.netlify.app/concepts/version-ranges/) vs [live version](https://operator-framework.github.io/operator-controller/concepts/version-ranges/)
=> 📖 Fix table formatting in the "Version ranges" doc

docs/howto/catalog-queries.md, docs/tutorials/explore-available-content.md
Think this works as desired. Check it please.
Fixes #1460
=> 📖 Simplify jq examples using olm.csv.metadata

docs/howto/derive-service-account.md, docs/howto/how-to-grant-api-access.md, docs/project/olmv1_architecture.md, docs/project/olmv1_design_decisions.md
Mostly fixes lists that render fine in GitHub, but not on the mkdocs website.
Also replaces several text notes with visual note blocks like we do in other places across our docs.
> [!TIP]
> We also have docs deployment preview. See the comment from netlify bot below.
> [!TIP]
> Recommend reviewing the changes with `git diff --ignore-all-space` (`-w`) option. GitHub UI also has this option.
>  ![Screenshot 2024-11-12 at 15 59 15](https://github.com/user-attachments/assets/d4c123d8-d6fb-4007-9e01-d4fbfed2e4d6)
=> 📖 Fix formatting in docs

docs/howto/how-to-channel-based-upgrades.md, docs/howto/how-to-pin-version.md, docs/howto/how-to-version-range-upgrades.md, docs/howto/how-to-z-stream-upgrades.md
There were several intentional breaking changes in the API which are now included in v0.18.0 release.
This commit mostly focuses on updating the documentation to reflect API changes. This includes making sure that snippets and example outputs match the current state of the project.
Relevant PRs:
* https://github.com/operator-framework/operator-controller/pull/1439
* https://github.com/operator-framework/operator-controller/pull/1434
=> 📖 Fix docs: "How to" section

CONTRIBUTING.md, docs/contribute/developer.md
* Removes mention of non-existing make targets
* Updates `kind create` snippet with correct one
=> 📖 Update contributor docs

docs/concepts/controlling-catalog-selection.md, docs/concepts/crd-upgrade-safety.md, docs/concepts/upgrade-support.md, docs/concepts/version-ranges.md
There were several intentional breaking changes in the API which are now included in v0.18.0 release.
This commit mostly focuses on updating the documentation to reflect API changes. This includes making sure that snippets and example outputs match the current state of the project.
Relevant PRs:
* https://github.com/operator-framework/operator-controller/pull/1439
* https://github.com/operator-framework/operator-controller/pull/1434
> [!TIP]
> We also have docs deployment preview. See the comment from netlify bot below.
> [!TIP]
> Recommend reviewing the changes with `git diff --ignore-all-space` (`-w`) option. GitHub UI also has this option.
>  ![Screenshot 2024-11-12 at 15 59 15](https://github.com/user-attachments/assets/d4c123d8-d6fb-4007-9e01-d4fbfed2e4d6)
=> 📖 Fix docs: "Conceptual Guides" section

docs/getting-started/olmv1_getting_started.md, docs/tutorials/upgrade-extension.md
With the addition of the CRD Upgrade Safety preflight check, our existing example of upgrading argocd from 0.5.0 to 0.6.0 no longer serves as a good example. This commit changes the example to use an update from 0.2.0 to 0.2.1 which no longer fails the CRD Upgrade check, and also doesn't violate our restriction on automatic upgrades between minor versions with a major version of 0.
Addresses #1459
=> 📖 Update extension upgrade tutorial doc

internal/catalogmetadata/cache/cache.go, internal/catalogmetadata/cache/cache_test.go, internal/controllers/clustercatalog_controller.go, internal/controllers/clustercatalog_controller_test.go, internal/controllers/clusterextension_controller.go
=> 🐛 catalog cache: retry cache population when cache contains an error

.github/workflows/go-apidiff.yaml
Now that our APIs are stable, we have made `go-apidiff` a required check in CI. As such, we need it to be enabled in the merge queue.
=> 🌱 enable go-apidiff in merge queue

internal/rukpak/convert/registryv1.go, internal/rukpak/convert/registryv1_test.go, internal/rukpak/convert/testdata/combine-properties-bundle/manifests/csv.yaml, internal/rukpak/convert/testdata/combine-properties-bundle/metadata/annotations.yaml, internal/rukpak/convert/testdata/combine-properties-bundle/metadata/properties.yaml
When we implemented support for including CSV annotations in chart metadata, we neglected to remember that bundle properties can also come from the `metadata/properties.yaml` file in the bundle filesystem. This PR updates the registry+v1 bundle converter library to read properties from `metadata/properties.yaml` (if it exists) and append any properties that are found into the `metadata.annotations["olm.properties"]` annotation in the CSV.
=> 🐛 combine bundle properties from csv and metadata/properties.yaml

go.mod, go.sum
Prep for v1.0.0 of operator-controller.
=> 🌱 Bump catalogd from v1.0.0-rc2 to v1.0.0

.github/workflows/release.yaml
It looks like ever since we enabled the merge queue, we've been pushing a bunch of merge queue built image tags to quay.
Check out the "gh-readonly-queue-main" tags at https://quay.io/repository/operator-framework/operator-controller?tab=tags&tag=latest
=> 🌱 gha: release: only push images for tags and main branch

docs/index.md
In order to try to be more transparent about our goals and current state.
=> 📖 add clarification about if is possible to migrate from V0 to V1

test/e2e/metrics_test.go
As described in the RFC https://docs.google.com/document/d/1hYOtHWcfoX_zWvy2YeolQBGuDgmP72vXMlrj9q9kPBQ/edit?tab=t.0 we would like to add the tests before get merge the PR:https://github.com/operator-framework/operator-controller/pull/1475 just to ensure that the metrics work at the same way before and after the changes.
Motivation: https://github.com/operator-framework/operator-controller/issues/1509
=> 🌱 e2e: add tests to validate metrics endpoint

CONTRIBUTING.md, Makefile, internal/controllers/suite_test.go
This change introduces downloading the specific binaries required to run ENVTEST-based tests into the project/bin directory. This setup makes configuring tests for debugging directly in an IDE easier.
1. **Ease of IDE Debugging**:
- By setting the `BinaryAssetsDirectory` dynamically, contributors can debug tests in their preferred IDEs (e.g., GoLand, VSCode) without requiring additional environment configuration such as setting `KUBEBUILDER_ASSETS`.
2. **Project-Specific Binaries:**
Installing binaries inside the project avoids conflicts with other projects or system-wide installations, particularly useful for contributors with restricted environments (e.g., corporate laptops).
The binaries installed by envtest-setup are no longer placed in the HOME/global directory. See the default …
=> 🌱 Configure ENVTEST Binaries for IDE Debugging

test/e2e/metrics_test.go
Depending on how e2e is run, we may not have a k8s client available.
=> :seedling: Add check for client in e2e

config/base/manager/kustomization.yaml, config/base/manager/service.yaml, config/base/rbac/kustomization.yaml, config/components/tls/resources/manager_cert.yaml, test/e2e/metrics_test.go
This PR renames the internal operator-controller service from "operator-controller-controller-manager-metrics-service" to "operator-controller-service".
It also moves the service kustomize manifest from the `rbac` base to the `manager` base.
=> 🌱 move service to kustomize manager dir, rename for general purpose use

hack/tools/catalogs/download-catalog
Small fix that changes the name of the catalogd service from `catalogd-server` to the currently used `catalogd-service` in the _hack/tools/catalogs/download-catalog_ script.
Changes separated from https://github.com/operator-framework/operator-controller/pull/1539 as per https://github.com/operator-framework/operator-controller/pull/1539#discussion_r1900596361
=> :bug: renamed catalogd service name in download-catalog hack script

internal/applier/helm.go, internal/applier/helm_test.go
<del>A few minor fixes:</del>
1. _internal/applier/helm.go:getReleaseState()_ contained two `if` blocks that handled  `driver.ErrReleaseNotFound` with the first one returning, which meant the second block would never run.
Additionally, the first handler always returned a `nil`  `desiredState` causing the only currently used `Preflight` validator (`crdupgradesafety`) and potentially others in the future to exit immediately because of not having anything to validate.
This fix leaves only the second handler block in, which actually triggers a dry-run installation and is able to return a proper `desiredState` that any `Preflight` validation can work with. It also has the added benefit of potentially spotting any issues and exiting earlier in case the dry-run failed.
<del>2. …
=> :bug: desired state in applier

hack/tools/catalogs/generate-manifests, hack/tools/catalogs/list-compatible-bundles, scripts/install.tpl.sh
Seems it's poor bash form to use the `function` keyword when defining functions. This PR cleans up our bash scripts in this regard.
=> :seedling: remove 'function' from function defs in bash scripts

RELEASE.md
After cut 1.0.0, we should follow semver
Therefore, this PR only removes the outdated and no relevant info
=> 📖  release: update the doc since it is no longer in a initial development

catalogd/test/e2e/metrics_endpoint_test.go
Follow op-con's lead on specifying a metrics address
=> 🐛 catalogd: e2e metrics: Do not use a fixed namespace for metrics tests

Makefile
The current bingo-upgrade make target can choke on bingo dependencies that require the whole path to the executable. For instance, golangci-lint needs to be installed with bingo as follows:
```
bingo get github.com/golangci/golangci-lint/cmd/golangci-lint
```
as opposed to:
```
bingo get github.com/golangci/golangci-lint
```
The update makes use of the 3rd column of the bingo list command:
```
$ bingo list
Name            Binary Name                                             Package @ Version                                                                       Build EnvVars   Build Flags
----            -----------                                             -----------------                                                                       -------------   -----------
bingo …
```
=> :bug: fix bingo-upgrade target

go.mod
=> ✨ Upgrade Golang from 1.22 to 1.23

Makefile
Noticed the test target references a no longer existent `generate-catalogd` target. Just cleaning that up.
=> :bug: remove reference to non-existent target

.github/workflows/e2e.yaml
E2E is failing due to an action we use which in turn uses a deprecated version of `actions/upload-artifact`. Confusingly, the article [here](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) states that this will happen on the 30th, and yet it's failing today ([example](https://github.com/operator-framework/operator-controller/actions/runs/12812852550/job/35725510412))
=> 🐛 Replace deprecated upload action for e2e

catalogd/internal/source/containers_image.go, cmd/operator-controller/main.go, internal/rukpak/source/containers_image.go, test/e2e/cluster_extension_install_test.go, testdata/images/catalogs/test-catalog/v1/configs/catalog.yaml
~NOTE: Same issue applies to catalogd, I'll make a similar change there.~ Done
With this change, operator-controller will be able to invalidate the configuration cache of `containers/image` and accept new configuration at runtime when changes occur.
~For code simplicity's sake, there's a few things to take note of that can be addressed if deemed necessary:~
* ~The cache always invalidates on the first unpack, as we've not yet read the `registries.conf` file. This is easily addressed but I wanted to keep `main()` clear of the file reading op.~
* ~We only check the `registries.conf` file. Checking the entire directory is more involved since we have to traverse the folder tree along with the symlinks dropped in there by k8s (`WalkDir` does not support symlinks , but it might [get …
=> 🐛 Fix operator-controller not using updated registries configuration

.github/workflows/e2e.yaml, test/e2e/cluster_extension_install_test.go, test/upgrade-e2e/post_upgrade_test.go, test/upgrade-e2e/upgrade_e2e_suite_test.go, test/utils/artifacts.go
* Mitigates the upgrade-e2e test flakiness caused by #1626 by waiting for the catalog's `last unpacked` to be after the catalogd deployment pod's creation time 
* Updates the upgrade-e2e test to also wait for the catalogd deployment to be up
* Factors out the artifact collection code into a `utils` package and adds artifact collection to upgrade-e2e
=> :bug: mitigate upgrade-e2e test flakiness

.gitignore
Adds `vendor` dir to .gitignore to avoid adding them by mistake
=> :seedling: add vendor dir to .gitignore

internal/rukpak/preflights/crdupgradesafety/checks_test.go, internal/rukpak/preflights/crdupgradesafety/crdupgradesafety.go
orderKappsValidateErr() is meant as a temporary solution to an external (ie. dependency) problem. carvel.dev/kapp/pkg/kapp/crdupgradesafety Validate() can return a multi-line error message which comes in random order. Until that is changed upstream, we need to fix this on our side to avoid falling into cycle of constantly trying to reconcile ClusterExtension's status due to random error message we set in its conditions.
An upstream PR is already created, but it might be some time before it makes it into the carvel's codebase and then to ours, hence this change. 
For full context please see https://github.com/operator-framework/operator-controller/issues/1456 and https://github.com/carvel-dev/kapp/pull/1047, especially https://github.com/carvel-dev/kapp/pull/1047#discussion_r1922017781
=> :bug: add orderKappsValidateErr in crdupgradesafety preflight

catalogd/internal/serverutil/serverutil.go, go.mod, internal/resolve/catalog.go
This adds more logging to help administrators troubleshoot issues resolving bundles from catalogs. Specifically, it:
- Adds logging to the catalogd http server, so that all requests are logged with useful metadata about the request and response
- Adds logging in the resolution code path to:
- report with catalogs are included in the resolution
- report whether the desired package is found in each catalog
- report the total count of bundles and the matched count of bundles in each catalog
This should help administrators narrow down which stage of resolution should be investigated when unexpected resolution errors occur.
=> ✨ improve logging: catalog http server, op-con resolver

.github/workflows/e2e.yaml
Replace cytopia/upload-artifact-retry-action with actions/upload-artifact
This is the same action that e2e-kind uses
cytopia/upload-artifact-retry-action uses an out-of-date upload-artifact action, and has been stale since Nov 2022
=> :bug: Fix upgrade-e2e, use updated upload-artifact

CONTRIBUTING.md
=> :book: Add go version information to contributing

.tiltignore
.tiltignore specifies files for Tilt to ignore when it does automatic rebuilds. Ignoring these common text files prevents unnecessary rebuilds.
=> ✨ Add .tiltignore

catalogd/hack/scripts/demo-script.sh
With the change we will use the operator-controller releases for catalogd demo script
Fixes  #1605
=> :bug: Use monorepo release for catalogd

catalogd/Makefile
Updating the make file to use operator-controller/releases/latest/download/install.sh
Fixes #1604
=> :bug: Update catalogd Makefile

Makefile
We have been working on an initiative to integrate the catalogd project into this repository.
As part of this effort, we released a candidate version to validate the changes made so far. During the v1.2.0-rc1 release, we identified the following issues:
- The installer script was not downloading the operator-controller.yaml file.
- The images defined for both projects in operator-controller.yaml were using the devel tag instead of the correct released version tag.
Following are the details...
After the release candidate v1.2.0-rc1, we could check that the installer is falling with
```
$ curl -L -s https://github.com/operator-framework/operator-controller/releases/latest/download/install.sh | bash -s
namespace/cert-manager unchanged …
```
=> 🐛  fix release artefacts after monorepo changes and release candidate 1.2.0-rc1

Makefile
* fix: the reference in the make quickstart to get the latest release version properly
* fix: replace the devel tag image with the version from the release
=> 🐛  fix release artefacts after monorepo changes

catalogd/Makefile
Fix the catalogd run-latest-release make target running in the wrong directory.
=> 🐛 Catalogd upgrade-e2e fix

catalogd/cmd/catalogd/main.go, cmd/operator-controller/main.go
Extensive e2e tests revealed that operator-controller and catalogd might run into leader election timeouts during cluster bootstrap, causing sporadic alerts being generated.
This commit uses recommended settings for leaderelection:
```
LeaseDuration: 15s -> 137s
RenewDeadline: 10s -> 107s
RetryPeriod:    2s ->  26s
```
Warning: This will increase potential down-time of our components to 163s in the worst case (up from 17s). (LeaseDuration + RetryPeriod)
=> 🐛 Set recommended leaderelection settings

catalogd/cmd/catalogd/main.go, catalogd/internal/source/containers_image.go, cmd/operator-controller/main.go, internal/rukpak/source/containers_image.go, internal/rukpak/source/containers_image_test.go, internal/rukpak/source/util.go, internal/util/fs.go
This addresses an intermittent failure we've seen where operator-controller appears to not resolve catalogs that exist. We identified the issue coming from the catalog caches not being valid after a restart.
This PR adds two things to address this issue:
- On startup of the binary, always clear the catalog cache directory
The PR also includes some small refactoring and fixes:
- moves certain unpack functions to an util package and are now shared by catalog and bundle image unpacker
- if unpack path happens to be an existing file, we delete it and unpack the image
=> 🐛 Ensure catalog caches are valid after restart

.goreleaser.yml, Makefile, scripts/install.tpl.sh
Closes: https://github.com/operator-framework/operator-controller/issues/1674
=> 🐛 fix install script and release to use and provide default-catalog

internal/httputil/certpoolwatcher.go, internal/httputil/certpoolwatcher_test.go
The SystemRoot store looks at the SSL_CERT_DIR and SSL_CERT_FILE environment variables for certificate locations. Because these variables are under control of the user, we should assume that the user wants to control the contents of the SystemRoot, and subsequently that those contents could change (as compared to certs located in the default /etc/pki location).
Thus, we should watch those locations if they exist.
=> :seedling: Add support for SSL env vars to cert pool watcher

catalogd/cmd/catalogd/main.go, catalogd/config/components/ca/patches/manager_deployment_cacerts.yaml, cmd/operator-controller/main.go, config/components/tls/patches/manager_deployment_cert.yaml
Rename the options that provide CAs to image pulling to indicate the use.
=> :sparkles: Separate CA configuration for pulls vs catalogd services

scripts/install.tpl.sh
The install script expects `default-catalog.yaml` to be present in the filesystem. But, it references an url. So, we remove the -f check and kubectl apply the url directly.
=> :bug: Fix default catalog installation in install script

catalogd/internal/source/containers_image.go, internal/fsutil/helpers.go, internal/fsutil/helpers_test.go, internal/rukpak/source/containers_image.go, internal/rukpak/source/containers_image_test.go, internal/rukpak/source/helpers.go, internal/rukpak/source/helpers_test.go
This fix is required because If there are read-only files or directories in the cache dir when the process starts up (which can easily happen in catalogd), then we can't delete them and error out instead. This fix tries to set the files writable before deleting them.
=> 🐛 EnsureEmptyDirectory should recursively set writable perms prior to delete

catalogd/cmd/catalogd/main.go, cmd/operator-controller/main.go
=> ✨ release leader election lease on manager cancellation

internal/applier/helm.go, internal/applier/helm_test.go, internal/features/features.go
Allows this work to be done behind a feature gate, allowing for testing and for the code to settle in before it starts affecting operations.
Name of the feature gate is, `PreflightPermissions`, see code and tests for usage.
Should be a no-op even if enabled, as there is currently no code behind it.
=> ✨ Add feature gate for preflight permissions

RELEASE.md
Add the backport policy.
RFC: https://docs.google.com/document/d/1y9CK8oodXvHpvWPsE3NjKjiYdhRiUE8xJclRRjOfre4/edit?usp=sharing
=> 📖 : Release: Add backport policy

catalogd/internal/storage/localdir.go, catalogd/internal/storage/localdir_test.go
The [RFC](https://docs.google.com/document/d/1s6_9IFEKGQLNh3ueH7SF4Yrx4PW9NSiNFqFIJx0pU-8/edit?usp=sharing) was updated to reflect a decision to change the new endpoint from $base/api/v1/query to $base/api/v1/metas.
This PR makes that change.
=> ⚠ (catalogd) Update query endpoint to metas endpoint

catalogd/Makefile
Fix for the catalogd version package path in the Makefile to ensure catalogd binary contains the correct version information.
See https://issues.redhat.com/browse/OCPBUGS-49866
=> 🐛 fix catalogd version variable paths in Makefile

catalogd/internal/storage/http_precoditions_check.go, catalogd/internal/storage/localdir.go
`checkPreconditions` already writes http.StatusNotModified to the writer. It also writes http.StatusPreconditionFailed in certain cases. Writing again could overwrite the status written by `checkPreconditions`. This PR fixes the issue.
Refers [the source](https://cs.opensource.google/go/go/+/master:src/net/http/fs.go;l=271-274) for correct usage.
Additionally un-exports previously exported function/variable in the copied code from net/http. 
Signed-off-by: Anik Bhattacharjee <anbhatta@redhat.com>
=> 🐛 (catalogd) Don't write to header after checking for Preconditions

catalogd/test/e2e/unpack_test.go
=> 🌱 (cleanup): Removing unused consts from catalogd/test/e2e/unpack_test.go

.golangci.yaml, Makefile
Remove 'make vet' from Makefile, simplify; keep 'vet' enabled in linting
=> 🌱 (cleanup): Remove 'make vet' from Makefile, simplify; keep 'vet' enabled in linting

catalogd/internal/storage/localdir.go
The metas endpoint was using `serverJSONLines` for serving queries that are parameterized, which copies content from a reader to the response writer under the hood. As a result no-parameterized query responses don't have range request support.
The endpoint was however using `http.ServeContent` for cases when no parameters were provided, which does have range request support.
This PR switches the `http.ServeContent` out for `serveJSONLines` to make sure metas endpoint is consistent in it's lack of support for range requests.
=> 🐛 (catalogd) `serveJSON` lines instead of `http.serverContent` for no-params

internal/authentication/tokengetter.go, internal/authentication/tokengetter_test.go, internal/controllers/clusterextension_controller.go, internal/controllers/clusterextension_controller_test.go, internal/controllers/suite_test.go
Wrap the service account not does not exist error message
=> 🐛 Wrap service account error to hide k8s error

test/e2e/metrics_test.go, test/utils/utils.go
Refactored the metrics endpoint tests by introducing reusable helper functions. This reduces duplication and improves maintainability across both tests.
Motivated by: https://github.com/operator-framework/operator-controller/issues/1712
=> 🌱 (cleanup): Refactor metrics endpoint tests by extracting shared helpers

catalogd/Makefile, catalogd/hack/scripts/generate-asciidemo.sh
Currently, the script does not work for mac env.
The change here ensure that it can work for linux and mac
See:
```
View the recording at:
https://asciinema.org/a/R4bFB4cTQaJSytvePHqLl8pNu
This asciinema CLI hasn't been linked to any asciinema.org account.
Recordings uploaded from unrecognized systems, such as this one, are automatically
deleted 7 days after upload.
If you want to preserve all recordings uploaded from this machine,
authenticate this CLI with your asciinema.org account by opening the following link:
https://asciinema.org/connect/054dd205-c559-4711-80ae-a01034074c79
```
Before the change made:
```
$ make demo-update
hack/scripts/generate-asciidemo.sh
hack/scripts/generate-asciidemo.sh: line 40: [: /var/folders/n4/j272tr6d7hq63mf7_skv6zr80000gn/T/d.EqBWI4NlpY: binary …
```
=> 🌱 fix demo-update script to support mac os envs

catalogd/Makefile
Follow up of: https://github.com/operator-framework/operator-controller/pull/1728
Issue (before change)
```
make build
/Library/Developer/CommandLineTools/usr/bin/make -C catalogd generate
stat /Users/camilam/go/src/github/operator-framework/operator-controller/catalogd/internal/version: directory not found
  Aft
```
After change:
The version has been obtained properly:
```
go build -tags 'containers_image_openpgp' -ldflags '-s -w -X "github.com/operator-framework/operator-controller/internal/version.gitVersion=v1.2.0-rc4-24-gd72e551-dirty" -X "github.com/operator-framework/operator-controller/internal/version.gitCommit=d72e5518c1605bde9359f643c44934c9885fdadf" -X "github.com/operator-framework/operator-controller/internal/version.gitTreeState=dirty" -X …
```
=> 🐛 fix catalogd binary version output.

docs/draft/howto/consuming-metrics.md
- Improved Metrics Consumption Documentation:
- Added a comprehensive guide for consuming metrics exposed by Operator-Controller and CatalogD services.
- Detailed steps to enable metrics, validate access using curl, and integrate securely with Prometheus Operator using ServiceMonitor
See the commands in this guidance executed with success 
```sh
$ kubectl create clusterrolebinding operator-controller-metrics-binding \
>    --clusterrole=operator-controller-metrics-reader \
>    --serviceaccount=olmv1-system:operator-controller-controller-manager
clusterrolebinding.rbac.authorization.k8s.io/operator-controller-metrics-binding created
$ TOKEN=$(kubectl create token operator-controller-controller-manager -n olmv1-system)
echo $TOKEN
<VALUE HIDDEN>
$ kubectl apply -f - <<EOF
> apiVersion: v1 …
```
=>  📖  (doc): Add a doc as a guidance to help users know how to consume the metrics and integrate it with other solutions

docs/tutorials/install-extension.md
Found one spot we missed on our docs when we changed `ClusterExtension.spec.source.catalog.{channel -> channels}`
=> 📖 Update install-extension.md

catalogd/cmd/catalogd/main.go, catalogd/internal/source/containers_image.go, cmd/operator-controller/main.go, go.mod, internal/catalogmetadata/client/client.go, internal/httputil/certlog.go, internal/httputil/certpoolwatcher.go, internal/httputil/certutil.go, internal/rukpak/source/containers_image.go
Logging now indicates what certificate (by file and X.509 name) is being watched
Update:
* Remove `firstExpiration` as it's no longer calculated
* Default logging to `V(4)`, using a constant
* Add cert logging for catalogd pull failure
Log when an unknown server cert is encountered:
```
E0203 20:46:01.629763       1 client.go:124] "unverified cert" err="Get \"https://catalogd-service.olmv1-system.svc/catalogs/operatorhubio/api/v1/all\": tls: failed to verify certificate: x509: certificate signed by unknown authority" logger="catalog-client" n=1 subject="" issuer="CN=olmv1-ca" DNSNames=["localhost","catalogd-service.olmv1-system.svc","catalogd-service.olmv1-system.svc.cluster.local"] serial="197916310015755767059581167694871409392"
```
Loading and Watching certificates:
```
I0203 …
```
=> :seedling: Add logging to certpoolwatcher and client

Makefile, catalogd/cmd/catalogd/main.go, cmd/operator-controller/main.go, go.mod, hack/ci/custom-linters/analyzers/analyzers_test.go, hack/ci/custom-linters/analyzers/setuplognilerrorcheck.go, hack/ci/custom-linters/analyzers/testdata/go.mod, hack/ci/custom-linters/analyzers/testdata/go.sum, hack/ci/custom-linters/analyzers/testdata/main.go, hack/ci/custom-linters/cmd/main.go, internal/contentmanager/source/internal/eventhandler.go
Solves the following issues and add a custom linter to avoid this scenario in the future:
- Closes; https://github.com/operator-framework/operator-controller/issues/1566
- Closes: https://github.com/operator-framework/operator-controller/issues/1556
Furthermore, it solves a similar scenario in the EventHandler code implementation found with the new custom linter check.  
Example os usage:
```sh
$ make lint
go build -tags containers_image_openpgp -o ./bin/custom-linter ./hack/ci/custom-linters/cmd
go vet -tags=containers_image_openpgp -vettool=./bin/custom-linter ./...
cmd/operator-controller/main.go:337:3: Incorrect usage of 'logger.Error(nil, ...)'. The first argument must be a non-nil 'error'. Passing 'nil' results in silent failures, making debugging harder.
🐛 **What is wrong?** …
```
=> 🐛 Fix: Prevent nil errors in log.Error to ensure proper logging and add custom linter to avoid this scenario in the future

Makefile, catalogd/Makefile
=> 🌱 manifest generation: ensure we always fully regenerate files

cmd/operator-controller/main.go, go.mod
Migrate operator-controller cli command handling to cobra
Maintain/update flag handling by migrating to cobra as requested @ https://github.com/operator-framework/operator-controller/issues/1650
Changes:
- Stopped using pflags, moved to cobra
- Changed how the version flag is processed, instead adding it as a subcommand
- Moved flag processing/validation out of main()
- Integrated cobra error handling with RunE while preserving setupLog error messages
=> ✨ Migrate operator-controller cli handling to cobra

catalogd/cmd/catalogd/main.go, go.mod
---
This PR migrates the command-line handling logic in the `cmd/manager/main.go` file to utilize the [[Cobra CLI framework](https://github.com/spf13/cobra)]. The migration simplifies flag handling, improves readability, and enhances the extensibility of the CLI for future development.
---
1. **Cobra Root Command**:
- Introduced the `rootCmd` for top-level command handling, providing a clean and standardized entry point for the CLI.
2. **Flag Migration**:
- Migrated all existing flags from the standard `flag` package to Cobra’s `cmd.Flags()` and `cmd.PersistentFlags()`.
3. **Subcommand Restructuring**:
- Refactored and restructured any existing subcommands under Cobra’s subcommand system.
4. **Helper Functions**:
- Refined the main function by extracting logic into dedicated helper …
=>  ✨ Migrate Command Handling to Cobra for Simplified Flag Management

catalogd/cmd/catalogd/main.go, cmd/operator-controller/main.go
Do ctrl.SetLogger() in init()
Check klog.V(4).Enabled() in run() (after flags have been parsed)
Closes: https://github.com/operator-framework/operator-controller/issues/1556
=> :bug: Initialize logging at correct time

hack/ci/custom-linters/analyzers/setuplognilerrorcheck.go, hack/ci/custom-linters/analyzers/testdata/main.go
=> 🌱 (enhance): Enhance custom linter setuplogerrorcheck description

dev/local-debugging-with-tilt-and-vscode.md, dev/podman/setup-local-env-podman.md
Adds a short doc on how to set up breakpoints with VSCode through Tilt. This isn't in the official website documentation, just in the /dev folder where we have an existing tutorial on setting up a kind registry with podman on mac.
=> 📖 Add dev doc on setting up live debugging

catalogd/testdata/catalogs/test-catalog.Dockerfile
We no longer use it.
Now, catalogd e2e tests are executed with operator-controller one and we are using its testdata instead.
=> 🌱 (cleanup): remove catalogd/testdata

.gitignore, .goreleaser.yml, Makefile
Use OPCON and CATD abbreviations to make things shorter (`OPERATOR_CONTROLLER` is quite long...)
Also, clean up .gitignore to remove references of the catalogd directory.
=> :seedling: Tidy Makefile

test/e2e/metrics_test.go
There’s potential for flakiness due to timing issues. For example, the TestOperatorControllerMetricsExportedEndpoint assumes that:
•	The ClusterRoleBinding and token are immediately effective.
•	The curl pod becomes ready promptly.
•	The metrics endpoint is available as soon as the pod is ready.
In slower or variable environments, these assumptions might not hold, leading to intermittent failures. Adding explicit waits or retry logic for each resource’s readiness could help mitigate race conditions.
To fix this, this PR:
•	Adds a generic retry helper that attempts a function up to 5 times with a 5-second delay between tries.
•	Wraps key steps in the metrics endpoint tests with the retry logic:
•	Creating the ClusterRoleBinding.
•	Generating the ServiceAccount token.
•	Creating the curl …
=> :bug: Add checks to catch race-driven panics in metrics endpoint e2e

test/e2e/metrics_test.go, testdata/images/bundles/test-operator/v1.0.0/manifests/testoperator.clusterserviceversion.yaml
We can make our e2e's significantly faster by making sure pods stop immediately. Setting `terminationGracePeriodSeconds: 0` means that kubelet will send the kill signal immediately.
This is okay in our tests because:
1. For test bundles, we're setting it in the bundle (this is not something OLM itself is doing)
2. For the metrics pod, we are fine to kill it immediately because we already have the info we need from the `kubectl exec` call that has already completed.
=> 🌱 e2e: make pods exit faster with `terminationGracePeriodSeconds: 0`

internal/shared/util/image/filters.go, internal/shared/util/image/filters_test.go
If a catalog or bundle image contains files with xattrs, that can cause the controller to fail to unpack the image. This PR unsets those attributes to avoid permission errors when writing files to disk.
=> 🐛 util/image: unset PAXRecords and Xattrs when applying files

Makefile
Omit non-existent catalogd test directory from UNIT_TEST_DIRS environment variable filter.
Update the UNIT_TEST_DIRS environment variable to remove references to the `catalogd/tests/` which no longer exist following the monorepo work detailed in issue https://github.com/operator-framework/operator-controller/issues/1646
=> :sparkles: Cleanup catalogd remnants in unit test dirs

Makefile
=> ✨ Upgrade cert-manager used from v1.15.3 to v1.17.1

.goreleaser.yml
f the release is created via the GitHub UI, GoReleaser fails because it detects that the release already exists. It should be configured to allow GoReleaser to update the existing release instead of failing.
Closes: https://github.com/operator-framework/operator-controller/issues/1591
More info: https://goreleaser.com/customization/release/#github
=> 🌱 (fix) .goreleaser.yml update release notes when release is created via GitHub UI

Makefile, config/base/common/namespace.yaml
Derive Kubernetes minor version from client-go for PSA label and combine the calls required to get the k8s version from go.mod
=> :bug: (fix): update PSA versions to match Kubernetes API version

config/base/common/namespace.yaml
Namespaces should be restricted by default instead of have granted additional not required permissions
=> 🐛 (fix) PSA enforcement: Move from baseline to restricted

Makefile, internal/shared/version/version.go
The `--version` doesn't output the source code commit ID. It refers to "vcs-ref" in the image instead of "io.openshift.build.commit.id". 
Setting the `GIT_COMMIT` value to `SOURCE_GIT_COMMIT` if empty (which is a corresponding downstream variable) will ensure that the version outputs the right commit ID as the code from this repo gets copied to another repo for building purposes.
=> 🐛bugfix for operator-controller not outputting the right commit ID in the version

Makefile, config/base/common/namespace.yaml
This reverts commit 620792ea70af80e59f854a91128c58cb5a74c6d2.
=> 🌱 Revert "(fix): update PSA versions to match Kubernetes API version"

Makefile, hack/demo/catalogd-demo-script.sh, hack/demo/catalogd-metas-demo-script.sh
- adds a demo for the metas catalog service endpoint (but does not make this part of regular CI, since it is currently dependent on deploying from local artifacts
- Fixes a bug in the Makefile where the VERSION attribute would be empty instead of undefined, and succeeds now only with valid (non-empty) input
[![asciicast](https://asciinema.org/a/706817.svg)](https://asciinema.org/a/706817)
=> 🌱 Add catalogd metas service demo

api/v1/clustercatalog_types.go, api/v1/clusterextension_types_test.go, api/v1/common_types.go, internal/operator-controller/conditionsets/conditionsets.go
conditionset.ConditionTypes was being used by the CluterExtension controller to `ensureAllConditionsWithReason` whenever a particular reason needed to be set for all of the ClusterExention's conditions. However, the `ConditionTypes` included a Condition Type `Serving`, which is not a ClusterExtension Condition(it is a ClusterCatalog condition).
This is causing the `Serving` condition to show up when a resolution fails, which is incorrect to begin with, and is then never cleared when the resolution succeeds at a later stage.
```
try to upgrade ClusterExtension to a non-exist version
$ kubectl patch ClusterExtension extension-77972 -p '{"spec":{"source":{"catalog":{"version":"0.2.0"}}}}' --type=merge
clusterextension.olm.operatorframework.io/extension-77972 patched
- lastTransitionTime: …
```
=> 🐛(fix) Remove "Serving" condition type from ConditionSets

docs/draft/api-reference/catalogd-webserver-metas-endpoint.md, docs/draft/howto/catalog-queries-metas-endpoint.md, docs/draft/tutorials/explore-available-content-metas-endpoint.md
Closes https://github.com/operator-framework/operator-controller/issues/1782
=> 📖 (docs) draft catalogd docs with new metas endpoint 

Makefile, test/e2e/cluster_extension_install_test.go, test/e2e/e2e_suite_test.go, test/e2e/metrics_test.go, test/utils/utils.go
Reverts operator-framework/operator-controller#1821
Why:
Shows that broke downstream sync:
- PR to isolate: https://github.com/openshift/operator-framework-operator-controller/pull/293
- Issue: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_operator-framework-operator-controller/293/pull-ci-openshift-operator-framework-operator-controller-main-openshift-e2e-aws/1901934653003010048
```
Container test exited with code 2, reason Error
---
AtLYimWkz7DCOeuqaA7PrCJS-wbhXQmD8O1rXmdeLmiqDOBD3_ozJIEpthKERXszTlhIvwTHnGzNBTQ0A_8NBOuk0cjndJSjAS81DyAihuS6ZrfASnlygdJeHaEmGiy2o_tIaEEPMoT64gComue4IVvVHkgPnUBn2XeW38xlymDNsOC8jFWml_3bmfA3_rQa9eN1YJjAyg7Ggy_jeV7KU9v-fnDoQGWlsnQV8kXy6FYAbIb1WUGXkuSF8GmpQPGGxDKFvNwhwyjTEz-CN_X1hc2x0t3Iq8BpqBzmfNopbMwFfCFnfaSu5YxTUN95Nmgupcht …
```
=> :bug: Revert ":bug: Client go version metrics endpoint test"

internal/catalogd/controllers/core/clustercatalog_controller.go, internal/catalogd/controllers/core/pull_secret_controller.go, internal/operator-controller/controllers/clustercatalog_controller.go, internal/operator-controller/controllers/clusterextension_controller.go, internal/operator-controller/controllers/pull_secret_controller.go
This change ensures that catalogd and operator-controller components have distinct controller names (e.g., for clustercatalog). It improves metric aggregation and troubleshooting by clarifying which controller is outputting logs, reducing reliance on user-provided context.
It is related to (Motivated by):
- https://github.com/operator-framework/operator-controller/issues/1607
- https://github.com/operator-framework/operator-controller/issues/1040
- https://github.com/operator-framework/operator-controller/issues/920
=> ✨ Add named for controller to distinguish components in logs

cmd/operator-controller/main.go
In this PR we just add the option to use pprof as it exists for catalogd.
The documentation which describes how to use them is in its specific PR: https://github.com/operator-framework/operator-controller/pull/1876/files
It is related to (Motivated by):
- https://github.com/operator-framework/operator-controller/issues/1607
- https://github.com/operator-framework/operator-controller/issues/1040
- https://github.com/operator-framework/operator-controller/issues/920
=> ✨ Add flag to allow usage of pprof in operator-controller (disabled by default) as it is available for catalogd

Makefile
Providing the capability for targets to adopt GO_BUILD_FLAGS if set in the environment.  Specifically, this is useful when shifting from a compile environment which assumes no vendoring to one which assumes vendoring. 
Existing uses for this were just for unit tests, so those have been shifted to a new GO_BUILD_EXTRA_FLAGS variable.
=> 🌱  adopt externally-set GO_BUILD_FLAGS

internal/operator-controller/rukpak/convert/registryv1.go, internal/operator-controller/rukpak/convert/registryv1_test.go, internal/operator-controller/rukpak/convert/validator.go, internal/operator-controller/rukpak/convert/validator_test.go, test/convert/generate-manifests.go
Closes #1883  #1884
Adds a small registry+v1 bundle validation framework composed of individual validation functions. It is extensible by adding new validation functions. Note that the validation framework is _not_ currently used. This will happen in a follow up PR because some refactoring will be needed of the convert/rukpak package and I didn't want to bloat the PR.
=> :sparkles: Add registry+v1 bundle validation framework

internal/operator-controller/applier/helm_test.go, internal/operator-controller/rukpak/convert/validator.go, internal/operator-controller/rukpak/convert/validator_test.go
Adds a bundle validation check against the package name to ensure it is defined in the RegistryV1 bundle structure. And does some tidying adding array pre-allocations
=> :sparkles: Add package name validation function

OWNERS, OWNERS_ALIASES, docs/OWNERS
Contributes to
- https://github.com/operator-framework/community/issues/107
- https://github.com/operator-framework/community/issues/108
- https://github.com/operator-framework/community/issues/109
- https://github.com/operator-framework/community/issues/110
- https://github.com/operator-framework/community/issues/111
- https://github.com/operator-framework/community/issues/112
- https://github.com/operator-framework/community/issues/113
- https://github.com/operator-framework/community/issues/114
This expands the existing [CODEOWNERS](https://github.com/operator-framework/operator-controller/blob/main/CODEOWNERS) file to prow's OWNERS/OWNER_ALIASES files in order to be able to support our contribution ladder.  
This will work with https://github.com/openshift/release/pull/63229 to inform …
=> 🌱 proposing github-->prow reviewer/approver mapping

internal/operator-controller/rukpak/convert/registryv1.go, test/convert/expected-manifests/argocd-operator.v0.6.0/all-namespaces/02_clusterrole_argocd-operator.v0.-3gkm3u8zfarktdile5wekso69zs9bgzb988mhjm0y6p.yaml, test/convert/expected-manifests/argocd-operator.v0.6.0/all-namespaces/04_clusterrolebinding_argocd-operator.v0.-3gkm3u8zfarktdile5wekso69zs9bgzb988mhjm0y6p.yaml, test/convert/expected-manifests/argocd-operator.v0.6.0/all-namespaces/11_deployment_argocd-operator-controller-manager.yaml, test/convert/expected-manifests/argocd-operator.v0.6.0/own-namespace/09_deployment_argocd-operator-controller-manager.yaml, test/convert/expected-manifests/argocd-operator.v0.6.0/single-namespace/09_deployment_argocd-operator-controller-manager.yaml
* Adds `dep.Spec.RevisionHistoryLimit = 1` to generated Deployment manifests to maintain OLMv0 compatibility [[link](https://github.com/operator-framework/operator-lifecycle-manager/blob/dfd0b2bea85038d3c0d65348bc812d297f16b8d2/pkg/controller/install/deployment.go#L181)]
* Fixes permissions in AllNamespaces mode. The namespace rules were not being added to the final set of rules.
Updates generated bundle resources to reflect these changes
=> :bug: Fix bundle to plain manifest conversion

internal/operator-controller/rukpak/convert/registryv1_test.go, internal/operator-controller/rukpak/util/testing/testing.go, internal/operator-controller/rukpak/util/testing/testing_test.go
Adds additional unit testing around rukpak/convert to facilitate the upcoming refactoring towards a bundle renderer
=> :seedling: Add more unit testing around rukpak/convert

.github/workflows/e2e.yaml, .github/workflows/unit-test.yaml, cmd/catalogd/main.go, cmd/operator-controller/main.go, go.mod
Use proper flags and remove use of logrus and klog
=> :bug: Fix log initialization

internal/shared/util/http/certlog.go, internal/shared/util/http/certutil.go
Some log levels were defaultLogLevel+1 (5), change those to defaultLogLevel (4)
=> :seedling: Update certpoolwatcher log levels

docs/draft/howto/profiling_with_pprof.md
This one as just a doc to show we can use pprof with the components
The usage of pprof can help us solve bugs and analyse issues
It is blocked by #1875 because we need to add a flag.
It is related to (Motivated by):
- https://github.com/operator-framework/operator-controller/issues/1607
- https://github.com/operator-framework/operator-controller/issues/1040
- https://github.com/operator-framework/operator-controller/issues/920
=> 📖 (doc): Add under the docs/draft how to profilling with pprof

.github/workflows/catalogd-demo.yaml
Fix the issue: 
```
Run make demo-update
./hack/demo/generate-asciidemo.sh -u -n catalogd-demo catalogd-demo-script.sh
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
100  5481  100  5481    0     0    997      0  0:00:05  0:00:05 --:--:--  1277
asciinema: …
```
=> 🌱 fix(ci): sanitize env for asciinema upload

cmd/catalogd/main.go, internal/catalogd/features/features.go, internal/operator-controller/features/features.go, internal/shared/util/featuregates/logging.go, internal/shared/util/featuregates/logging_test.go
As a followup to #1858 and working from #1922 we add similar logging to the catalogd side of things.
=> ✨ Log catalogd feature gate states

internal/operator-controller/applier/helm.go, internal/operator-controller/authorization/rbac.go, internal/operator-controller/authorization/rbac_test.go
This PR contains 2 changes:
- Adds an errors.Join() to properly expand a list of errors that might include nil errors
- Adds explicit rule examples to 2 of the test cases
=> 🐛 OCPBUGS-55165 Permissions preflight error output fixes

internal/operator-controller/applier/helm_test.go, internal/operator-controller/controllers/clusterextension_controller.go
Adds another test case to helm_test.go for when PreAuthorize() returns missing RBAC rules.
=> ✨ Reformat error wrapping for resolved bundle status

internal/operator-controller/rukpak/convert/registryv1.go, internal/operator-controller/rukpak/render/render.go, internal/operator-controller/rukpak/render/render_test.go
This PR updates the BundleRenderer's Render method signature by removing the targetNamespaces parameter as a required parameter in favor of making it an option. It also adds additional unit tests around options and fixes an NPE caused by passing nil as the options parameter.
=> :seedling: Make target namespaces optional

.github/workflows/go-verdiff.yaml
This appears to be confusing the jobs reporting.
=> :bug: Add path to job workflow for go-verdiff

.github/workflows/go-verdiff.yaml, codecov.yml
1) Remove path from now-required go-verdiff CI
We're experiencing a weird behavior with this CI being required, and running only on certain paths.
2) Add a 2% threshold for codecov
=> :bug: Ease CI requirements for go-verdiff and codecov

.github/workflows/go-verdiff.yaml, hack/tools/check-go-version.sh
Rather than disabling the go-verdiff CI to allow it to pass when there is a legitimate golang version change, use a label to override the test results.
The label is `(override-go-verdiff)`.
=> :seedling: Allow override of go-verdiff result via label

cmd/operator-controller/main.go, internal/operator-controller/features/features.go, internal/operator-controller/rukpak/render/certproviders/openshift_serviceca.go, internal/operator-controller/rukpak/render/certproviders/openshift_serviceca_test.go
Adds openshift-serviceca certificate provider support for webhooks. Enabled via feature gate: `WebhookProviderOpenshiftServiceCA`
=> :sparkles: Add openshift-serviceca certificate provider

internal/operator-controller/rukpak/convert/helm.go, test/e2e/cluster_extension_install_test.go, testdata/images/bundles/test-operator/v1.0.0/manifests/bundle.configmap.yaml
Some registry+v1 manifests may actually contain Go Template strings that are meant to survive and actually persist into etcd (e.g. to be used as a templated configuration for another component). In order to avoid applying templating logic to registry+v1's static manifests, we create the manifests as Files, and then template those files via simple Templates.
=> 🐛 fix: don't template registry+v1 manifests

codecov.yml
Update codecov patch threshold
We often see +/- very small changes to the patch threashold which end up reporting as a failure. Set the threshold to 1% so these -0.05% changes don't impact us as much.
=> :seedling: Ease CI requirements for codecov patch

test/e2e/cluster_extension_install_test.go, testdata/images/bundles/test-operator/v1.0.0/manifests/bundle.configmap.yaml, testdata/images/bundles/test-operator/v2.0.0/manifests/bundle.configmap.yaml, testdata/images/bundles/test-operator/v2.0.0/manifests/olm.operatorframework.com_olme2etest.yaml, testdata/images/bundles/test-operator/v2.0.0/manifests/testoperator.clusterserviceversion.yaml, testdata/images/bundles/test-operator/v2.0.0/metadata/annotations.yaml, testdata/images/catalogs/test-catalog/v2/configs/catalog.yaml, testdata/push/push.go
Follow-up on #1979:
- make upgrade-e2e pass again
- fix ClusterExtensionInstallReResolvesWhenCatalogIsPatched
=> :bug: fix install and upgrade e2es

docs/draft/api-reference/network-policies.md
=> 📖 Add NetworkPolicy doc

go.mod, go.sum
This adds Network Policy support.
=> ✨ Update operator-registry to v1.55.0

.gitignore, .goreleaser.yml, Makefile
In anticipation of config changes.
Use environment variables for the release values.
Update the Makefile to use the same variables.
=> :sparkles: Update releaser to use env variables

internal/operator-controller/rukpak/render/certproviders/certmanager.go, internal/operator-controller/rukpak/render/certproviders/certmanager_test.go
Currently, the generated webhook certificate is set to rotate 1 year before expiry. In this PR we set it to 24h to keep parity with OLMv0 behavior.
=> :bug: Fix webhook service rotation to renew within 24h of expiry

internal/operator-controller/rukpak/render/certprovider.go, internal/operator-controller/rukpak/render/certprovider_test.go, internal/operator-controller/rukpak/render/certproviders/certmanager.go, internal/operator-controller/rukpak/render/certproviders/certmanager_test.go, internal/operator-controller/rukpak/render/certproviders/openshift_serviceca_test.go, internal/operator-controller/rukpak/render/registryv1/generators/generators.go, internal/operator-controller/rukpak/render/registryv1/generators/generators_test.go, internal/operator-controller/rukpak/render/registryv1/registryv1.go, internal/operator-controller/rukpak/render/registryv1/registryv1_test.go
Minor refactor renaming the WebhookServiceGenerator and WebhookService attribute in the cert provider configuration. The naming is not accurate in the sense that the service is not necessarily exclusive to webhooks. In some future, if we want to implement, e.g. APIService support, the same service will be used. These are rather services that are backed by the deployments in described in the CSV.
=> :seedling: Bundle renderer refactor webhook service related function and attribute naming

internal/operator-controller/rukpak/render/registryv1/generators/generators.go, internal/operator-controller/rukpak/render/registryv1/generators/generators_test.go
1. Removes the APIService volume mount - since we don't yet support APIServices (let's avoid adding things that aren't needed yet)
2. Moves the tls.crt and tls.key magic strings to constants
3. Addresses the following bug:
When installing the Red Hat Network Observability operator, we were faced with the following error:
```
"error for resolved bundle \"network-observability-operator.v1.7.0\" with version \"1.7.0\": failed to create resource: Deployment.apps \"netobserv-controller-manager\" is invalid: spec.template.spec.containers[0].volumeMounts[2].mountPath: Invalid value: \"/tmp/k8s-webhook-server/serving-certs\": must be unique",
```
The root cause is related to the operator's `Deployment`'s `Pod` template spec described in the CSV that included a volume mount pointing to the webhook …
=> :bug: Fix webhook cert duplicate volume mount path bug

.tilt-support, config/base/catalogd/manager/manager.yaml, config/base/operator-controller/manager/manager.yaml
This makes our containers' root filesystems read-only, which improves security by preventing writes to the container’s base image filesystem.
It adds `/tmp` as an emptyDir volume so that our app can continue writing temporary files as needed.
=> ✨ set `readOnlyRootFilesystem: true` for workloads

internal/catalogd/controllers/core/clustercatalog_controller.go, internal/catalogd/controllers/core/clustercatalog_controller_test.go, internal/operator-controller/controllers/clusterextension_controller.go, internal/operator-controller/controllers/clusterextension_controller_test.go
This is necessary to ensure that we do not keep reconciling the objects as if they were not deleted.
The need for this became apparent while trying to use --cascade=orphan with a ClusterExtension. In theory, that should work out of the box because, we set owner references on all managed objects.
However, that was not working because our controller was fully reconciling objects with metadata.finalizers: ["orphan"], which was writing owner references back into the objects that the orphan deletion process had just removed.
Ultimately this meant that the managed objects would be background deleted because they once again had an owner reference to the now-deleted ClusterExtension, which then caused the kubernetes garbage collector to clean them up.
In general, it stands to reason that once we …
=> 🐛 short-circuit reconcile when objects are deleted

docs/draft/howto/consuming-metrics.md
Updates the docs around metrics gathering to include necessary NetworkPolicy, and fixes some errors in the ServiceMonitor yaml for securityContext and catalogd labels.
=> 📖 Metrics Docs Maintenance

test/e2e/network_policy_test.go
This PR introduces a new e2e test to continuously validate the NetworkPolicy objects for the catalogd and operator-controller components. 
The new test, `TestNetworkPolicyJustifications`, achieves the following:
* Documents NetworkPolicies deployed: A registry of all allowed network policies (`allowedNetworkPolicies`) is defined using the [RFC: OLMv1 Static Network Policies](https://docs.google.com/document/d/1bHEEWzA65u-kjJFQRUY1iBuMIIM1HbPy4MeDLX4NI3o/edit?tab=t.0#heading=h.x3tfh25grvnv). Every rule within these policies is explicitly registered in the registry with a clear, written justification of a minimum length. This ensures that every rule's purpose is documented and understood.
* Prevents Regressions: The test validates that the NetworkPolicy objects deployed in the cluster …
=> ✨OPRUN-3873: Add e2e tests for NetworkPolicies

test/e2e/network_policy_test.go
Follow up to [2034](https://github.com/operator-framework/operator-controller/pull/2034)
When there is a dual namespace deployment, the default-deny-all policy is duplicated in both namespaces.
This PR updates the list of `allowedPolicies` to include both policies if a dual namespace deployment is detected.
=> 🐛 (e2e) fix default-deny-all in list of allowed policies for test

Makefile, hack/test/setup-monitoring.sh, kind-config.yaml
Closes #1902 and #1903
Adds prometheus to the `test-e2e` Makefile target, which stands up a barebones prometheus scraper to gather metrics from the operator-controller and catalogd pods during the e2e test run. When finished, the prometheus server is queried for a raw output of the metrics and stores it in `ARTIFACTS_PATH/metrics.out`. These metrics will be analyzed in a later PR.
=> 🌱 Add prometheus to e2e workflow

Makefile, api/v1/clustercatalog_types_test.go, config/base/catalogd/crd/experimental/olm.operatorframework.io_clustercatalogs.yaml, config/base/catalogd/crd/kustomization.yaml, config/base/catalogd/crd/standard/olm.operatorframework.io_clustercatalogs.yaml, config/base/operator-controller/crd/experimental/olm.operatorframework.io_clusterextensions.yaml, config/base/operator-controller/crd/kustomization.yaml, config/base/operator-controller/crd/standard/olm.operatorframework.io_clusterextensions.yaml, go.mod, go.sum, hack/tools/crd-generator/README.md, hack/tools/crd-generator/main.go, hack/tools/crd-generator/main_test.go, hack/tools/crd-generator/testdata/api/v1/clusterextension_types.go, hack/tools/crd-generator/testdata/api/v1/groupversion_info.go, hack/tools/crd-generator/testdata/output/experimental/olm.operatorframework.io_clusterextensions.yaml, hack/tools/crd-generator/testdata/output/standard/olm.operatorframework.io_clusterextensions.yaml, hack/tools/update-crds.sh, internal/operator-controller/controllers/suite_test.go, manifests/standard.yaml
Fix #2014
Add support for a new CRD generator. This generator will use `opcon`
tags to identify experimental features. A script runs the CRD
generation, and creates all the CRDs.
New experimental CRDs are now created.
=> :warning: OPRUN-3954: Update CRD generator to support experimental CRDs

hack/test/setup-monitoring.sh
`Endpoints`, which Prometheus uses by default, are now fully deprecated since kind has been updated and we need to add configuration to tell Prometheus to use `EndpointSlices` instead.
=> 🐛 Fix Prometheus Using Endpoints

Makefile, config/base/catalogd/kustomization.yaml, config/base/operator-controller/kustomization.yaml, config/components/base/common/kustomization.yaml, config/components/base/experimental/kustomization.yaml, config/components/base/standard/kustomization.yaml, config/overlays/basic-olm/kustomization.yaml, config/overlays/experimental/kustomization.yaml, config/overlays/standard-e2e/kustomization.yaml, manifests/experimental.yaml
Fix #2015 
This adds `manifests/experimental.yaml`
The difference between the experimental manifest and the standard manifest is the presence of the experimental CRD vs the standard CRD (as of right now there is only a difference in annotations), and the feature-gated components.
This change supports defining feature components in _exactly_ one place:
* GA'd features are put into `components/base/common`
* Feature-Gated/Experimental/TechPreview features are put into `components/base/experimental`
This adds new components to make constructing the overlays easier:
`components/base/common` includes everything but CRDs and experimental features:
* `base/catalog` (but not CRDs)
* `base/operator-controller` (but not CRDs)
* `base/common`
* GA'd features (currently none) …
=> :seedling: OPRUN-3955: Add experimental manifest

.github/workflows/e2e.yaml, Makefile, codecov.yml, config/overlays/experimental-e2e/kustomization.yaml, manifests/experimental-e2e.yaml, test/experimental-e2e/experimental_e2e_test.go
This adds `manifests/experimental-e2e.yaml`, and uses it to run the experimental-e2e.
The experimental-e2e is run via `make test-experimental-e2e` and a CI job is added to run it.
A "no-op" experimental-e2e test has been added.
This is part of the feature-gated API functionality.
=> :seedling: Add experimental e2e tests

config/README.md, config/components/base/common/kustomization.yaml, config/components/base/standard/kustomization.yaml
Also update config comments to make it clear where features are supposed to be listed.
=> :seedling: Update config readme

.tilt-support, Makefile
The go.mod version of cert-manager was updated to v1.18.2
=> :seedling: Update additional cert-manager locations to v1.18.2

config/base/catalogd/crd/experimental/olm.operatorframework.io_clustercatalogs.yaml, config/base/catalogd/crd/standard/olm.operatorframework.io_clustercatalogs.yaml, config/base/operator-controller/crd/experimental/olm.operatorframework.io_clusterextensions.yaml, config/base/operator-controller/crd/standard/olm.operatorframework.io_clusterextensions.yaml, config/overlays/basic-olm/kustomization.yaml, config/overlays/experimental-e2e/kustomization.yaml, config/overlays/experimental/kustomization.yaml, config/overlays/standard-e2e/kustomization.yaml, config/overlays/standard/kustomization.yaml, config/overlays/tilt-local-dev/catalogd/kustomization.yaml, config/overlays/tilt-local-dev/operator-controller/kustomization.yaml, hack/tools/crd-generator/main.go, hack/tools/crd-generator/testdata/output/experimental/olm.operatorframework.io_clusterextensions.yaml, hack/tools/crd-generator/testdata/output/standard/olm.operatorframework.io_clusterextensions.yaml, manifests/experimental-e2e.yaml, manifests/experimental.yaml, manifests/standard-e2e.yaml, manifests/standard.yaml
The feature-set annotation was originally applied by the crd-generator to the generated CRDs. Now, that annotaion is being added by the overlay, and is being added to all resources in the manifest.
Each manifest has an annotation value based its name.
The crd-generator is now adding a generated annotation indicating what the CRD was generated for.
=> :sparkles: Add feature-set annotation to all manifest resources

internal/operator-controller/rukpak/render/registryv1/generators/generators.go, internal/operator-controller/rukpak/render/registryv1/generators/generators_test.go
Sets the NamespaceSelector in generated Validating and MutatingWebhookConfiguration resources. This ensures that webhooks for operators installed in single/own namespace mode are (at least for namespaced APIs) restricted to the target namespace of the installation.
The implementation diverges from that of OLMv0. In OLM v0 the namespace selector is derived from OperatorGroup labels OLM sets on the target namespaces. In OLMv1 we don't have OperatorGroups and there's probably no need to add any labels to target namespaces. So, we use the kubernetes provided "kubernetes.io/metadata.name" label. This may not work in older versions of kubernetes.
Note: the renderer itself supports rendering the bundle manifests for multi-namespace mode. OLMv1 just doesn't support MultiNamespace mode. Therefore, …
=> :sparkles: Add NamespaceSelector to generated webhook configs

config/components/base/experimental/kustomization.yaml, manifests/experimental-e2e.yaml, manifests/experimental.yaml
We are not planning on doing the synthetic auth in light of the boxcutter effort.
=> :seedling: Remove synthetic auth from experimental manifests

Makefile
Using `find .` will delete all files of the name, this has a wide blast radius downstream. Limit the set of `find` directories to those in upstream.
#2091 breaks downstream, this reduces the blast radius.
=> :bug: When generating, delete only upstream targets

codecov.yml
Did you know you can validate your codecov.yaml file?
```
curl -X POST --data-binary @codecov.yml https://codecov.io/validate
```
Our codecov.yaml file was not valid, now it is.
Really hoping this makes small percentage errors not block merges.
=> :seedling: Update codecov.yaml to be valid

test/experimental-e2e/experimental_e2e_test.go, testdata/images/bundles/webhook-operator/v0.0.1/manifests/webhook-operator-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml, testdata/images/bundles/webhook-operator/v0.0.1/manifests/webhook-operator.clusterserviceversion.yaml, testdata/images/bundles/webhook-operator/v0.0.1/manifests/webhook.operators.coreos.io_webhooktests.yaml, testdata/images/bundles/webhook-operator/v0.0.1/metadata/annotations.yaml, testdata/images/catalogs/test-catalog/v1/configs/catalog.yaml
Depends on #2107 to pass
Adds a basic webhook support e2e to the experimental e2e suite. 
We should consider building a little e2e test library as there will be much re-use between the tests and the streams (standard, experimental, etc.). Alternatively, maybe we should consider not having multiple e2e test suites and use labels or some other artifice to to structure/select what gets run in which scenario. This might also make it easier to re-use helper functions and always ensure that the e2e suite is concise and consistent as features graduate.
=> :seedling: Add basic webhook support e2e

config/components/cert-manager/ca/issuers.yaml, config/components/cert-manager/catalogd/resources/certificate.yaml, config/components/cert-manager/operator-controller/resources/manager_cert.yaml, manifests/experimental-e2e.yaml, manifests/experimental.yaml, manifests/standard-e2e.yaml, manifests/standard.yaml, testdata/build-test-registry.sh
This removes the following warning by explicitly setting the value to the default:
```
Warning: spec.privateKey.rotationPolicy: In cert-manager >= v1.18.0, the default value changed from `Never` to `Always`.
```
=> :bug: Clear cert warning during deployments

.bingo/.gitignore
bingo overwrites the .gitignore file, so it can create an unexpected merge conflict.
Leave the OWNERS file in place (unless we discover that it is also a problem later).
=> :bug: Do not add OWNERS to bingo's .gitignore

.github/workflows/e2e.yaml, Makefile, hack/test/e2e-coverage.sh
Give the experimental-e2e it's own set of output files for coverage vs the regular e2e.
=> :seedling: Separate the (experimental-)e2e coverage

test/e2e/cluster_extension_install_test.go
Modify the `RecoversFromInitialInstallFailedWhenFailureFixed` test to instead not create the namespace and service account, instead of having bad service account. Boxcutter will ignore the service account.
Add `RecoversFromExsitingDeploymentWhenFailureFixed` test to ensure we don't adopt, and instead fail when there's an existing resource that matches the bundle (i.e. don't adopt),
=> :seedling: Update e2e tests for boxcutter

.github/workflows/e2e.yaml, Makefile
Now all testing targets start with "test".
=> :sparkles: Add "test" prefix to the extension-developer-e2e

test/e2e/cluster_extension_install_test.go, test/e2e/e2e_suite_test.go
* Update busybox deployment SecurityContext
* Don't panic at end of e2e test if PrintSummary fails
=> :bug: Fix downstream e2e test compatibility

.github/workflows/e2e.yaml, config/overlays/prometheus/prometheus_rule.yaml, test/e2e/e2e_suite_test.go, test/utils/summary.go, test/utils/templates/summary.md.tmpl
Adds prometheus alerts for excessive API calls from operator-controller or catalogd, as well as summary graphs to match.
Do not fail e2e run when issues with summary generation are encountered or when the output isn't specified.
=> ✨ API Call Alerts

.github/workflows/e2e.yaml, Makefile, hack/test/pre-upgrade-setup.sh
Adds a make task and github workflow for running upgrade tests against the experimental e2e release. The intent is for this to be an "informing" job pre-merge, not a blocking job.
=> 🌱 Makefile: add test-upgrade-experimental-e2e

README.md
Adds unit-test/e2e/codecov badges to README.md.
The token in codecov is meant to be used by third-parties.
=> :book: Add badges to README.md

internal/operator-controller/applier/helm.go, internal/operator-controller/applier/helm_test.go, internal/operator-controller/rukpak/bundle/registryv1.go, internal/operator-controller/rukpak/convert/helm.go, internal/operator-controller/rukpak/convert/helm_test.go
Put watchNamespace in config. 
Work for [RFC​: Config -> registry+v1 bundle config](https://docs.google.com/document/d/1rmcT8tXcezjq0Iy3Cde097Y8ZaCgUXhEgiuyfv1vXUI/edit?usp=sharing)
=> ✨ OPRUN-4090: (rukpak) Add config support for reg+v1 bundle to chart converter

internal/operator-controller/rukpak/render/render.go, internal/operator-controller/rukpak/render/render_test.go
Updates registry+v1 renderer to compute target namespace defaults based on the bundle's install mode configuration:
- bundle supports AllNamespaces: default is [""] (install in AllNamespaces mode)
- bundle supports OwnNamespace: default is [<install-namespace>]
- bundle supports neither AllNamespaces or OwnNamespace mode: undefined (user must specify TargetNamespaces)
We also update the targetNamespace validation to ensure the own namespace cannot be used unless OwnNamespace install mode is supported
=> :sparkles: OPRUN-4113: Compute target namespace defaults

go.mod, hack/kind-config/containerd/certs.d/go.mod
=> 🐛 retract v1.5.0; exclude hack/kind-config/containerd/certs.d from root module

go.mod, hack/kind-config/containerd/certs.d/go.mod
Back port of #2202
* retract v1.5.0; exclude hack/kind-config/containerd/certs.d from root module
* fixup! retract v1.5.0; exclude hack/kind-config/containerd/certs.d from root module
* fixup! retract v1.5.0; exclude hack/kind-config/containerd/certs.d from root module
---------
=> 🐛 retract v1.5.0; exclude hack/kind-config/containerd/certs.d from root module [release-v1.5]

helm/olmv1/templates/rbac/clusterrolebinding-operator-controller-manager-rolebinding.yml, manifests/experimental-e2e.yaml, manifests/experimental.yaml
This should finally fix `test-upgrade-experimental-e2e`.
=> :bug: OPRUN-4128: Rename opcon manager CRB when boxcutter is enabled

helm/tilt.yaml
When the move was made to use helm charts for the Tilt configuration, the TLS components were not added. This means in the current state, both operator-controller and catalogd will exit on launch due to metrics-bind-address requiring the tls-key and tls-cert. This PR adds the certManager option to fix this issue.
=> ✨ Fix Tilt by adding certManager option to the tilt.yaml chart

Makefile
It is not referred in any of CI workflows, nor documented in the contribution guide.
Also, its usage is questionable given that it tries to upgrade all tools to the latest version at once.
Typically such upgrades are performed in a more controlled way, one PR per tool, either by developer
or dependbot.
Developers are still able to initiate an update by invoking
```
bingo get foo@x.y.z
```
=> :seedling: OPRUN-4138 Remove `bingo-upgrade` Makefile target

test/e2e/metrics_test.go
The short name was causing downstream issues:
```
image name curlimages/curl:8.15.0 returns ambiguous list
```
Using the long name seems to fix this.
Already tested downstream.
=> :bug: Use long name for curl image

internal/operator-controller/rukpak/preflights/crdupgradesafety/crdupgradesafety.go, internal/operator-controller/rukpak/preflights/crdupgradesafety/crdupgradesafety_test.go, internal/operator-controller/rukpak/preflights/crdupgradesafety/testdata/manifests/crd-unhandled-new.json, internal/operator-controller/rukpak/preflights/crdupgradesafety/testdata/manifests/crd-unhandled-old.json, internal/operator-controller/rukpak/preflights/crdupgradesafety/unhandled_message_test.go
We use the **crddiff**   (https://github.com/kubernetes-sigs/crdify) library to check API differences and ensure CRD upgrade safety. See: [CRD upgrade safety docs](https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/extensions/cluster-extensions#crd-upgrade-safety)  
When crddiff cannot handle the diff, it reports an **unhandled scenario**.  
In this case, a **full JSON diff** is returned which **causes the problem**
- The JSON is **too large** to update in the CR status.  
- This causes an error:  `Too long: may not be more than 32768 bytes</code>`  
**-As a result:**  
- **ClusterExtension is not upgraded**.  
- **Users see no information** about why the upgrade failed.  
- The only details are hidden in confusing logs in the operator-controller deployment, …
=> 🐛 (fix): unhandle changes for crd upgrade safety ( OCPBUGS-59518 )

cmd/operator-controller/main.go, internal/operator-controller/applier/provider.go, internal/operator-controller/applier/provider_test.go
The RegistryV1HelmChartProvider was letting through bundles that don't support AllNamespaces mode.
RegistryV1HelmChartProvider is updated to handle the SingleOwnNamespace feature in the same way the Webhook feature is handled. In a follow-up PR, GetWatchNamespace() (which checks for the SingleOwnNamespace feature) will be moved into this component. 
Note: This PR used to have an e2e tests to ensure bundles not supported by the standard OLMv1 profile get rejected. But, there's currently no way to execute an e2e test on the standard profile only. So, I've removed it and will add in a follow up PR once we've addressed this the right way.
=> :bug: OCPBUGS-62021: Fix install mode support gating
