operator-framework/operator-controller

api/v1alpha1/platformoperator_types.go
controllers/platformoperator_controller.go

Starting with a small change to address a `TODO` comment about breaking some logic out into its own function. Also cleaning up some code generation.

refactor(controller): add candidateBundles type for getting latest Bundle

---

.gitignore
Makefile
config/crd/bases/platform.openshift.io_platformoperators.yaml
config/manager/manager.yaml
config/samples/fbc/Dockerfile
config/samples/fbc/sampleCatalog/operators.yaml
config/samples/platform.openshift.io_sample_catalog.yaml
config/samples/platform.openshift.io_v1alpha1_platformoperator.yaml
controllers/platformoperator_controller.go
go.mod
go.sum
main.go

Add BundleInstance Generation

---

controllers/platformoperator_controller.go

controllers: Add support for watching BundleInstance resources

---

Makefile

With v0.4.0, adding the new version to the Makefile.

chore: upgrade rukpak

---

.github/workflows/ci.yaml
Makefile

.github,Makefile: Add golangci-lint to build dependencies

---

.golangci.yaml
Makefile
go.mod
test/e2e/README.md
test/e2e/controller_test.go
test/e2e/fbc_provider.go
test/e2e/generate.go
test/e2e/magic_catalog.go
test/e2e/platform_operators_suite_test.go
test/e2e/testdata/prometheus.yaml
test/e2e/util.go

Follow-up to #18 and #21 and adds some basic e2e tests.

ci: Add basic e2e testing suite

---

controllers/platformoperator_controller.go
internal/applier/applier.go
internal/sourcer/filter.go
internal/sourcer/source.go
internal/util/util.go
main.go

*: Refactor controller implementation

---

api/v1alpha1/platformoperator_types.go
config/crd/bases/platform.openshift.io_platformoperators.yaml

api,config: Add a short name for the PO API

---

Makefile
cmd/main.go
config/manager/manager.yaml
config/rbac/role.yaml
controllers/cs_adapter_controller.go
controllers/platformoperator_controller.go
deppy/config/manager/manager.yaml
internal/sourcer/registry_sourcer.go
internal/sourcer/sourcer.go

Summary: Introduces a new controller that's responsible for watching and reading CatalogSources in the cluster, and modeling individual bundles in a catalog as Input resources that the deppy component can consume.

*: Introduce a CatalogSource deppy adapter

---

.github/workflows/ci.yaml

.github/workflows: Update the verify job to run the correct Makefile target

---

.github/workflows/ci.yaml
Makefile
test/e2e/collect-ci-artifacts.sh
test/e2e/operators_test.go
test/e2e/util.go

*: Ensure testing artifacts are gathered when running in CI

---

api/v1alpha1/operator_types.go
config/crd/bases/operators.operatorframework.io_operators.yaml

Signed-off-by: Joe Lanford <joe.lanford@gmail.com>

make Operator API cluster-scoped

---

internal/resolution/entitysources/catalogdsource.go

Replaces "olm.bundle.path" with a constant

---

config/manager/manager.yaml

add PSA labels to namespace for restricted enforcement

---

CONTRIBUTING.md
DCO

Add DCO information

---

.github/dependabot.yml

🌱 Prefix dependabot GH actions PRs

---

go.mod
go.sum

Subj. Just dependency bump.
Will need it to complete #459 (see https://github.com/operator-framework/operator-controller/issues/459#issuecomment-1810756032)

🌱 Upgrade Deppy

---

cmd/manager/main.go
cmd/resolutioncli/main.go
go.mod
go.sum
internal/controllers/operator_controller.go
internal/controllers/suite_test.go

New version contains breaking changes: solver interface changed slightly (e.g. no `Solution` wrapper anymore).

🌱 Bump Deppy to v0.3.0

---

cmd/manager/main.go
internal/controllers/extension_controller.go
internal/controllers/suite_test.go

✨remove unused extension reconciler fields

---

.github/workflows/e2e.yaml
.github/workflows/unit-test.yaml

:seedling: bump codecov to v4 token-based

---

config/samples/olm_v1alpha1_extension.yaml

Sample included fields which do not exist.
Fixes #638

🌱 Update `Extension` sample

---

.github/ISSUE_TEMPLATE/docs-issue.md

Add a docs issue template for epics

:book: Add docs issue template for epics

---

internal/controllers/clusterextension_controller.go
internal/rukpak/source/image.go
internal/rukpak/util/labels.go

:warning: Update owner keys

---

go.sum

:sparkles: Run 'go mod tidy'

---

internal/catalogmetadata/types.go
internal/controllers/clusterextension_controller.go

:sparkles: Fix some lints

---

cmd/manager/main.go
internal/controllers/clusterextension_controller.go

✨  Getting cluster extension running

---

internal/controllers/clusterextension_controller.go
internal/controllers/clusterextension_controller_test.go
internal/packageerrors/packageerrors.go
internal/resolution/variablesources/required_package.go
internal/resolution/variablesources/required_package_test.go

:sparkles: Consolidate error message generation

---

cmd/manager/main.go

Improve performance by caching objects that only have ClusterExtension as owners.

:sparkles: Improve caching 

---

cmd/manager/main.go

:sparkles: Really fix linter

---

Makefile

:bug: Fix shell in Makefile

---

api/v1alpha1/clusterextension_types.go
cmd/manager/main.go
internal/catalogmetadata/types.go
internal/controllers/clusterextension_controller.go
internal/controllers/suite_test.go
internal/labels/labels.go

:sparkles: Address reviews

---

README.md

🌱 stupid typo

---

Makefile

:bug: Separate make fix-lint from make vet

---

go.mod
go.sum

🌱bump catalogd to v0.19.0

---

CONTRIBUTING.md
README.md
docs/components.md
docs/drafts/version-ranges.md

📖 Remove references to Deppy in documentation

---

.github/workflows/add-to-project.yaml

🌱 add v1.0 and v1.x issues to OLMv1 project automatically

---

.bingo/README.md

Bingo will overwrite this, which can cause issues.
This reverts commit 1d64a4d4252deb719550b40ca7246fe44ab8d86c.

:bug: Revert "Update .bingo/README.md"

---

Makefile
go.mod
go.sum

:seedling: Update catalogd to v0.23.0 and cert-manager to v1.15.3

---

docs/Tasks/adding-a-catalog.md

:book: Remove reference to catalogd phase field

---

README.md
docs/Tasks/exploring-available-packages.md
docs/Tasks/installing-an-extension.md
docs/Tasks/uninstalling-an-extension.md
docs/drafts/Tasks/create-installer-service-account.md
docs/drafts/Tasks/downgrading-an-extension.md
docs/drafts/Tasks/upgrading-an-extension.md
docs/drafts/refs/olmv1-limitations.md
mkdocs.yml

- Quickstart changes:
- simplified + added links to other more detailed documents
- added placeholders for the following documents:
- drafts/refs/olmv1-limitations.md
- drafts/Tasks/create-installer-service-account.md
- added drafts/Tasks/upgrading-or-downgrading-an-extension.md
- updated install/uninstall task mds with links to other docs

:book:[Docs] Update quickstart documentation

---

docs/drafts/how-to-version-range-upgrades.md

:book: [Docs] Fix How-to: Version Range Automatic Updates

---

docs/index.md

[1] https://github.com/operator-framework/operator-controller/blob/main/docs/olmv1_overview.md

:book: Fixing the olmv1_overview reference in the index.md

---

.github/workflows/sanity.yaml
.gitignore
Makefile

Also simplifies the verify github action.
Background: https://github.com/operator-framework/operator-controller/pull/1240#discussion_r1757416835

🌱 Clean up catalogd API Ref generation

---

docs/drafts/developer.md

Replace kube context mention;
Improve Mac brew usage

📖 [Docs] Improve developer.md

---

mkdocs.yml

- Enable mermaid.js via https://squidfunk.github.io/mkdocs-material/reference/diagrams/#configuration

📖 [Docs] Enable diagram support via mermaid.js

---

README.md

:book: Adding the docs website to the readme

---

internal/features/features.go

We do not use this feature gate, but it appears in `--help` message.

🌱 Remove `EnableExtensionApi` feature gate

---

cmd/manager/main.go
config/samples/catalogd_operatorcatalog.yaml
docs/api-reference/catalogd-api-reference.md
docs/concepts/controlling-catalog-selection.md
docs/getting-started/olmv1_getting_started.md
docs/howto/how-to-version-range-upgrades.md
docs/tutorials/add-catalog.md
go.mod
go.sum
hack/test/pre-upgrade-setup.sh
internal/catalogmetadata/client/client.go
internal/catalogmetadata/client/client_test.go
internal/controllers/clustercatalog_controller.go
internal/controllers/clustercatalog_controller_test.go
internal/controllers/clusterextension_controller.go
internal/resolve/catalog.go
internal/resolve/catalog_test.go
internal/scheme/scheme.go
test/e2e/cluster_extension_install_test.go
test/e2e/e2e_suite_test.go
test/extension-developer-e2e/extension_developer_test.go
test/upgrade-e2e/post_upgrade_test.go

:warning: Bump catalogd to v1

---

docs/howto/how-to-version-range-upgrades.md

🌱 fix minor typo

---

docs/contribute/developer.md

Follow up for https://github.com/operator-framework/operator-controller/pull/1443#discussion_r1836909713

📖 Update wording in the developer docs

---

hack/tools/check-go-version.sh

:bug: Fix go-verdiff check to handle new .mod files

---

go.mod
go.sum

Prep for v1.0.0-rc2 of operator-controller.

🌱 Bump catalogd from v1.0.0-rc1 to v1.0.0-rc2

---

docs/project/olmv1_roadmap.md

:book: Adding deprecation notice to roadmap

---

.gitignore
.idea/.gitignore
.idea/catalogd.iml
.idea/modules.xml
.idea/vcs.xml

Remove IDE (idea) files and fix .gitgnore

🌱 Remove IDE (idea) files and fix .gitgnore

---

go.mod
go.sum

Bumps kapp dependency to latest release

:seedling: bump carvel.dev/kapp to v0.64.0

---

internal/catalogd/controllers/core/clustercatalog_controller_test.go

This is a follow-up from the previous PR #421 i.e. commit d320249c3bf485420716b96c9e823ddb536eab25

:seedling: Adding additional unit test for catalog availability

---

go.mod
go.sum

🌱 Upgrade upgraded golang.org/x/exp v0.0.0-20241009180824-f66d83c29e7c => v0.0.0-20250228200357-dead58393ab7

---

test/e2e/network_policy_test.go

The test was previously listing networkpolicies to validate only in the namespace operator-controller is deployed in.
Upstream, that is valid since the namespace that operator-controller is deployed in, is the namespace that all other components are deployed in (and therefore all the network polices we expect to find).
A different distribution of olmv1 (downstream) could decide to deploy the policies in different namespaces, in which case the test will not look into all the namespaces it should look into.
This PR fixes the issue by searching in the namespaces both operator-controller and catalogd is deployed in.

🐛 (e2e) fix namespaces network-policy test searches in

---

config/base/catalogd/crd/experimental/olm.operatorframework.io_clustercatalogs.yaml
config/base/catalogd/crd/standard/olm.operatorframework.io_clustercatalogs.yaml
config/base/operator-controller/crd/experimental/olm.operatorframework.io_clusterextensions.yaml
config/base/operator-controller/crd/standard/olm.operatorframework.io_clusterextensions.yaml
hack/tools/crd-generator/main.go
hack/tools/crd-generator/testdata/output/experimental/olm.operatorframework.io_clusterextensions.yaml
hack/tools/crd-generator/testdata/output/standard/olm.operatorframework.io_clusterextensions.yaml
manifests/experimental-e2e.yaml
manifests/experimental.yaml
manifests/standard-e2e.yaml
manifests/standard.yaml

🌱 crd-generator annotation text: generated -> generator

---

internal/shared/util/testutils/summary.go

The template paths for the e2e summary didn't come along for the migration 🙃

🌱 Update Template Paths

---

hack/tools/update-tls-profiles.sh

🌱 fix: make hack/tools/update-tls-profiles.sh work on macOS
